### ISSUE TITLE
[doc] Best-practise to use with complex objects

### ISSUE THREAD

**Issue by marxsk** [poteto/ember-changeset#133]
I'm using ember-changeset with more complex objects. Let's assume:

    this.properties = Ember.A();
    this.properties.pushObject({name: 'name', level: 'advanced', type: 'text', title: 'My Name', value: '123'});
    this.properties.pushObject({name: 'city', type: 'select', title: 'City', value: 'Brno', options: ['Brno', 'Praha', 'New York']});
    this.properties.pushObject({name: 'author', level: 'advanced', type: 'text', title: 'Author', value: null, defaultValue: 'Hugo Hugo'});
 
what differs from expected

    this.properties = { name: 'My Name', city: 'Brno', author: null }

My question is what is the best practise to use more complex objects? 

Currently, my solution is to use computed properties to generate expected format from my complex one. It works but I believe there might be a better option.

**Comment by Mithrilhall** [comment]
@marxsk Could you post what you're doing with computed properties? I'm running into the same problem.

**Comment by marxsk** [comment]
@Mithrilhall Sure. I don't have a final commit on github yet but I had to create a component that encapsulate form generation to be able to use computed property.

    simpleProperties: Ember.computed('properties.@each.value', {
       get() {
       let ret = {};
       this.get('properties').forEach(function(x) {
          ret[x.get('name')] = x.get('value');
       });
       return ret;
    }}),

The explicit get() is there because I was thinking about setting computed property. Later I have decided that it would not help me that much. 

In the controller, I have following action:

    submitProperties: function(properties, changeset) {
      // update values locally
      for (let attrName in changeset.get('change')) {
        properties.forEach(function(item, index) {
          if (item.get('name') === attrName) {
            item.set('value', changeset.get(attrName));
          }
        });
      }

      // save changes to remote server
      this.store.pushClusterProperties(changeset);
    }

**Comment by Mithrilhall** [comment]
@poteto Is flattening the object the recommended way to deal with nested objects?

From:

```{
  "firstName": "William",
  "lastName": "Wallace",
  "address": {
    "country": "United States of America",
    "state": {
      "name": "Alaska",
      "abbreviation": "AK",
      "town": {
        "name": "Barrow",
        "coordinates": {
          "latitude": "71.29056",
          "longitude": "-156.788666"
        }
      }
    }
  }
}
```

To:

```
{
  "firstName": "William",
  "lastName": "Wallace",
  "address.country": "United States of America",
  "address.state.name": "Alaska",
  "address.state.abbreviation": "AK",
  "address.state.town.name": "Barrow",
  "address.state.town.coordinates.latitude": "71.29056",
  "address.state.town.coordinates.longitude": "-156.788666"
}
```

**Comment by snewcomer** [comment]
Nested object support is in > 1.4
