### ISSUE TITLE
Not returning the full promise from Changeset#save causes unhandled rejections when save fails

### ISSUE THREAD

**Issue by jon-hall** [poteto/ember-changeset#136]
Spent a while debugging my API failure-case tests today (returning a 500 using mirage) as they were getting unhandled rejections, it eventually seems to be caused by `save` chaining a `then` call internally but returning the 'pre-`then`' promise.  This might be due to how `RSVP` works, or could be something else, but modifying `save` to return the 'full' promise like:

```js
return savePromise.then((result) => {
  this.rollback();
  return result;
});
```
Stops the uncaught rejections and gets the tests working again.

It looks like someone else has already had this issue and put in a PR to fix it (#135), wanted to put up a corresponding issue as supporting info for the PR. :+1:

**Comment by snewcomer** [comment]
Thank you!
