### ISSUE TITLE
Using ember-changeset with objects containing an array

### ISSUE THREAD

**Issue by BartTK** [poteto/ember-changeset#138]
I want to use ember-changeset for an object containing an array. When I create a changeset based on the following model:

`
{
	"someField": "someValue",
	"someArray": [
		"value1",
		"value2"
	]
}
`

And I do a `changeset.set('someArray.0', 'newValue1')`, it does not work. Debugging shows that the new value is not registered as a change, but it is applied directly on the original model. 

What happens here is that Ember first does a `changeset.get('someArray')` and then sets the property on the resulting object. On the first get, the `unknownProperty` handler of ember-changeset returns the original array (as it has not been changed yet). The set is then applied on the original array and not on the changeset.

Can this be fixed? This is probably related to the issues dealing with complex objects #127 and #133.

**Comment by poteto** [comment]
The support isn't great right now but essentially changeset expects you to create a new array and then set the property to refer to the new array

**Comment by edborden** [comment]
I just ran into this issue. I tried https://github.com/DockYard/ember-changeset/pull/141 unsuccessfully, so I followed @poteto 's suggestion above like so:
```
      changeset = new Changeset(model, lookupValidator(CampaignValidations), CampaignValidations);
      let rawTimes = model.get('times').toArray();
      changeset.set('times', rawTimes);
```
This successfully passes through any changes to `changeset.times` when `changeset.save()` is called, where before it was resetting.
Hoping to be able to drop this workaround in the future, but for now it's not too painful.

**Comment by jbailey4** [comment]
Does the same workaround apply to nested objects?

**Comment by poteto** [comment]
@jbailey4 Yup!

**Comment by dyoganand** [comment]
A computed property listening on an array property inside a changeset is triggered twice.

`watchDraft: Ember.computed('myChangeset.cc_emails.[]', function() {
  // triggered twice when cc_emails is being changed
})`

**Comment by hornetnz** [comment]
This also appears to be a problem with rollback. Fields using a nested key don't revert. Does anyone know if the https://github.com/DockYard/ember-changeset/pull/140 changes will fix that?

**Comment by manuelsalvatori** [comment]
For me, the workaround doesn't work.
I have a model with two arrays, I tried different combinations of settings but in conjunction with a multi-select, when I change selections it doesn't update the changeset arrays correctly.

**Comment by kszambelanczyk** [comment]
Poteto workaround works, but that gives us a changeset with dirty status, and that is problem too

**Comment by ashrafhasson** [comment]
setting the changeset property to a new array doesn't seem to set `isDirty` on it.

**Comment by cottrellio** [comment]
I just ran into this problem with a nested array of complex objects. I used the above workaround but I did a deep copy on the array of objects:
```javascript
// route.js
setupController(controller, model) {
  const changeset = new Changeset(model);
  const rawRules = JSON.parse(JSON.stringify(get(model, 'rules')));

  set(changeset, 'rules', rawRules);
  set(controller, 'changeset', changeset);
},
```
Then, in my rollback action, I had to do the same again (Or else rollback will only work once):
```javascript
// controller.js
actions: {
  async rollbackRuleset(changeset) {
    // get(this, 'model').rollbackAttributes();
    await changeset.rollback();
    const rawRules = JSON.parse(JSON.stringify(get(changeset, 'rules')))

    set(changeset, 'rules', rawRules);

    return changeset;
  },
},
```

**Comment by snewcomer** [comment]
@cottrellio what version are you using?

**Comment by cottrellio** [comment]
@snewcomer I'm on `"ember-changeset": "^1.5.0-beta.0",`

**Comment by snewcomer** [comment]
In 3.0.0-beta.0, `changeset.set` is the way to work with all types of situations.  `Ember.set` will cause issues.  `ember-changeset` doesn't rely on EmberObject anymore!
