### ISSUE TITLE
Return _content after `execute` instead of this

### ISSUE THREAD

**Issue by dustinfarris** [poteto/ember-changeset#139]
Right now `changeset.execute()` [returns the changeset itself](https://github.com/DockYard/ember-changeset/blob/55cf62a006ee9edee5f25cc37c7e95188b3a78fa/addon/index.js#L157).  I am not sure how this return value is used in the wild.

I'm envisioning a DDAU flow where changeset is handed a copy of an object, and execute returns it with changes applied.

```js
changeset = new Changeset(Object.assign({}, myObject));
```

and somewhere else down the line in a "saveObject" method or something like that:

```js
actions: {
  saveMe(changeset) {
    myCoolSaveFn(changeset.execute());
  }
}
```

I was looking at a similar idea in #82 which was closed immediately after opening.  This would be a breaking API change.

**Comment by Nuzsk** [comment]
@dustinfarris perhaps it should be a new method of getting raw content object?

example:
```
actions: {
  saveMe(changeset) {
    myCoolSaveFn(changeset.execute().raw());
  }
}
```
