### ISSUE TITLE
Issue with ember data models and obj.hasOwnProperty(key) from last release?

### ISSUE THREAD

**Issue by gordonbisnor** [poteto/ember-changeset#150]
I'm running into an issue where I have ember-changeset and ember -changeset validations installed on a form:

- Orignal Field X value = FOO
- Set Field X to BAR
- Set Field X to FOO
- If I am using an input, value now equals FO
- User is thus unable to make a change and cancel it

I have been attempting to isolate this by removing other removing parts, and have also tested in a new project.   

Not 100% sure if this is an ember-changeset, or a misunderstanding on my end at this point.

**Comment by gordonbisnor** [comment]
I see this line in index.js is the cause of my troubles:    

```js
   if (!isEqual(oldValue, value))
```

Assume this is intentional behaviour and that I am thus missing some concept of how this is meant to work.

**Comment by gordonbisnor** [comment]
Alternately, I notice that if I resolve my model's promise in the route's model hook before creating the changeset, I have no problem. Looks like this relates to code added in the most recent release 1.2.2

**Comment by snewcomer** [comment]
Going to close this for now as we have completely rewritten the internals.  Also we refactored this type of logic as well - `} else if (key in obj) {`.

Thank you for the issue (even though is old!)
