### ISSUE TITLE
Ember change set object not being modified with mut helper

### ISSUE THREAD

**Issue by leondmello** [poteto/ember-changeset#154]
I'm trying to use the `mut` helper to change the property of a changeset when a dropdown option is selected. The `mut` helper works fine if I use with a raw Ember model object. It doesnt seem to set some values when I use it with a changeset object.
This [repository](https://github.com/leondmello/ember-changeset-mut-bug) reproduces the issue.
There a two drop downs, one with a changeset and one without.

**Comment by leondmello** [comment]
Might be a duplicate of https://github.com/DockYard/ember-changeset/issues/153

**Comment by leondmello** [comment]
This bug was added in [1.2.2](https://github.com/DockYard/ember-changeset/releases/tag/v1.2.2)
1.2.1 is working fine

**Comment by poteto** [comment]
Thanks for reporting! Will investigate.

**Comment by aonawale** [comment]
Any update on this? I'm having the same issue.

**Comment by NLincoln** [comment]
I've found a minimal repro of what I believe is the same issue https://ember-twiddle.com/343eb036473f83a8332cb83d6a878497?openFiles=twiddle.json%2C

**Comment by snewcomer** [comment]
Just to notify everyone, `2.0.0-beta.0` has been published for ember-changeset and ember-changeset-validations.  Give it a shot!  @NLincoln

**Comment by snewcomer** [comment]
`changeset-set` is the canonical way to set a nested property in templates.  `changeset.set` will work in .js as well!
