### ISSUE TITLE
Regression in 1.2.2: defaultValue and booleans

### ISSUE THREAD

**Issue by karellm** [poteto/ember-changeset#156]
I'm using `one-way-checkbox` with `ember-changeset`. It looks like if I set a `defaultValue` on a model attribute, the checkbox acts all weird: [Twiddle](https://ember-twiddle.com/e4e5b5a08eb78927680e57a872f29c82).

I'm not sure if it is this project's fault or `ember-one-way-controls`, especially since it works fine if I don't use a changeset. I opened the same ticket there: https://github.com/DockYard/ember-one-way-controls/issues/151

**Comment by karellm** [comment]
It is really weird, I find myself in situation where I can't set `true` for a boolean value. It basically stay stuck to `false`. I would greatly appreciate some help on this issue! Thanks!

**Comment by karellm** [comment]
I think I have identified a regression in `1.2.2`. [Here](https://github.com/DockYard/ember-changeset/commit/49fe967d4699d4117b7becfcc167f7958ce4f784#diff-7562eb8eba3c3d86a671045f8c70107eR455) when the boolean is `false` and changed to `true`, for some reason `oldValue` is `true` (should be false). 

I'm reverting back to `1.2.1` for the time being and will try to submit a failing test case next week.

**Comment by mattmarcum** [comment]
👍 I'm seeing this error trying to mod a model's boolean property, also using a default value.

https://ember-twiddle.com/4277931580090cea4b3efcec04ed0743/c16063240f222ab1bd1f66f02f62dd23e0867821?numColumns=0

**Comment by karellm** [comment]
I updated the title to reflect that it is not related to `ember-one-way-controls`.

**Comment by timmyomahony** [comment]
I also noticed this using a checkbox `{{input ... type='checkbox' checked=changeset.isChecked}}` within a component. Reverting to v1.2.1 fixes the issue. Haven't tried 1.2.3 to see if the issue has been resolved.

**Comment by snewcomer** [comment]
Just to notify everyone, `2.0.0-beta.0` has been published for ember-changeset and ember-changeset-validations.  Give it a shot!

**Comment by snewcomer** [comment]
3.0.0 beta series also is published!  Setter issues should be much less common.
