### ISSUE TITLE
Regression since 1.2.2 due to isEqual function

### ISSUE THREAD

**Issue by remithomas** [poteto/ember-changeset#163]
We have a case where in our _changeset_ we set an array of models (relationships). 
All changes aren't correct applied because [isEqual](https://github.com/DockYard/ember-changeset/blob/master/addon/index.js#L495) don't evaluate array of models. 

Maybe is the same reason for https://github.com/DockYard/ember-changeset/issues/156 what do you think @bgentry ?

**Comment by nucleartide** [comment]
@remithomas Since it's been awhile, I'm going to close this. Please open a new issue if you're still running into the problem.
