### ISSUE TITLE
Question about complex use case

### ISSUE THREAD

**Issue by eccegordo** [poteto/ember-changeset#171]
HI

Trying to use ember changeset. Looks like a great library. Curious about some of the more advanced applications of this addon. Are there any somewhat complex use cases you could point me to or add in the documentation as reference examples?

In particular deeply nested objects and complex merge behaviors.

Also wondering about the changeset of changesets case. Can you roll a queue of changes and execute a save or rollback operation that cascades through an array of changesets? 

Let me sketch a use case by way of a UI example.

![workarea-card](https://cloud.githubusercontent.com/assets/497659/25067815/9c85e15c-2203-11e7-83b3-8c0a390b1d9c.png)

With this UI I have a series of steps and inside each step is potentially a different form backing a specific model/object

But wrapping this is a single save button (and potentially cancel button too) that can recursively work through all the change sets. I don't want the user to have to click a save for each form. The save operation needs to potentially work on multiple changesets.

My initial thought is to create a changes queue or array in the controller and dynamically push the changesets onto that stack and then handle the saves in a sequential fashion.

Couple problems I foresee.

1.) How to trigger the save events without user interaction (e.g. clicking a button) I could debounce and just send up a change set every time a change happens within a local form. But wondering about a pattern where you subscribe to `changeset.changes`.
 
2.) How do I handle complex merges? What if I have two change sets for the same model but it is not clear which is correct to save? Ember Concurrency perhaps?

**Comment by nucleartide** [comment]
Your `changes` queue/array idea sounds good.

1. Could you elaborate here? Do you want to trigger a `save` on the entire array of changesets on input?
2. `Changeset` does have a [`merge` function](https://github.com/poteto/ember-changeset#merge) – would that work for you?

**Comment by snewcomer** [comment]
Closing only b/c of time.  Seems interesting but would need more info to solve!
