### ISSUE TITLE
Support Warnings

### ISSUE THREAD

**Issue by brandynbennett** [poteto/ember-changeset#174]
Context
--------
Using `ember-changeset-validations`. Our UI designs have a concept of showing "warning" messages that alert the user that their input may be less than desirable but isn't invalid. When a form field has a warning the data should still be allowed to be set on the model and the user should be allowed to submit successfully. 

Desired Solution
-----------------
Ideally I would like to be able to flag certain validations in my validation maps as "warnings" and when `ember-changeset` sees the warning validation it adds it to the error array, decorates it as a warning so that it can be styled differently, and doesn't make the changeset invalid. This would allow me to do something this in a `validated-field` component
```javascript
// validation-map.js
export default {
  validateNumber({
    isWarning: true,
    integer: true,
  });
};
```

```hbs
{{!-- validated-field.hbs --}}
{{#each errors as |error|}}
  <li class=(if error.warning "is-warning" "is-error")>
    {{error.message}}
  </li>
{{/each}}
```

Current workaround
--------------------
My current workaround for this is to create two changesets one with a "warnings" validation map and one with an "errors" validation map. Then in my form component I merge the errors from the two changesets and decorate them as "errors" or "warnings".

**Comment by nucleartide** [comment]
@brandynbennett Excellent suggestion. (Sorry for getting back to you so late!)

I think this could be implemented if `Changeset` were more extendable – going to label this under `extensibility`.

**Comment by viniciussbs** [comment]
I like the idea of warnings but I think they should no be mixed with errors. Maybe provide an API similar to the error's API.

- `warning`
- `warnings`
- `addWarning`
- `pushWarnings`
- and so on
