### ISSUE TITLE
Can we point validate to a specific validation name?

### ISSUE THREAD

**Issue by hornetnz** [poteto/ember-changeset#175]
`
                        {{validated-field
                                type="text"
                                changeset=changeset
                                property="workEmail"
                                validateProperty=(action "validateProperty" changeset "workEmail")
                        }}
`

With the above, the action passes in the changeset and the propertyName 'workEmail'. I'm wondering if an optional third parameter could be added to point to which validation you want it to use?

`
export default {
    firstName: [
        validatePresence(true),
        validateLength({min: 2})
    ],
    lastName: [
        validatePresence(true),
        validateLength({min: 2})
    ],
    workEmail: [
        validateFormat({type: 'email'})
    ]
};
`

ie: instead of it using the validator that matches the propertyName, it would be nice to use a generic 'email' validation name that I can use on multiple fields of the same type. Or, is there an existing way to do it?

**Comment by nucleartide** [comment]
@hornetnz You should do that at the validation map level. For example:

```js
// (If you want to avoid repetition.)
const validateName = [validatePresence(true), validateLength({ min: 2 })];

export default {
  firstName: validateName,
  lastName:  validateName,
  workEmail: [validateFormat({type: 'email'})]
};
```
