### ISSUE TITLE
Question: Is it possible to extend Changeset class ?

### ISSUE THREAD

**Issue by janmisek** [poteto/ember-changeset#178]
I am looking into possibility to add custom computed properties on changeset.  Is it possible to extend Changeset class?

Thanks in advance.

**Comment by SuperCoolFrog** [comment]
The addon exports the class which is an ember object that you can extend on.  
I wrote this quick twiddle but it should point you in the right direction.
[Twiddle](https://ember-twiddle.com/e8db2f5a2165942e96e9378be3ebba57)

Extend API Guide
https://emberjs.com/api/classes/Ember.Object.html#method_extend

**Comment by janmisek** [comment]
Thanks alot for explanation I found myself yesterday. 

I would also suggest to include this info in readme, because export of `changeset` class is nowhere documented, default export is "ember-non-extensible" constructror function. 

Btw: why the original ember class is wrapped to classic js constructor function exported by default - is it to make original class semi-private or the reason is e.g typescript compat.

**Comment by bgentry** [comment]
The example in that Twiddle doesn't actually work. If you use that method, then the changeset's `obj`, `validationMap`, etc are all fixed to the default values and there is no way to change them. It does not appear that the Changeset class is actually extensible.

Is that intentional? Does it need to be that way?

**Comment by snewcomer** [comment]
We should ensure this works with 3.0.0....

**Comment by snewcomer** [comment]
This is now documented in the README!
