### ISSUE TITLE
EMBER-CLI-MIRAGE test fails at execute() in changeset.save()

### ISSUE THREAD

**Issue by shakeebatme** [poteto/ember-changeset#180]
Fails trace, 

```
save: function save(options) {
...
this.execute();//<-- Step in here. 
...
}
```
```
execute: function execute () {
  if(get(this,  'isValid') && get(this,  'isDirty')) {
    //not going inside if. I printer isValid and isDirty in action both are true. When I perform through browser changeset works as expected. 
  } 
}
```

**Comment by shakeebatme** [comment]
I commented out if condition from node-module  the Mirage Test case passes successfully without any issue. Please let me know the fix.

**Comment by poteto** [comment]
What exactly is failing?

**Comment by nucleartide** [comment]
@shakeebatme Closing this since it's been open for awhile without any follow-up. If you're still running into the problem, please [submit a new issue](https://github.com/poteto/ember-changeset/issues/new) and fill out the issue template. 🙂
