### ISSUE TITLE
Better handling of fields with POJOs on `.save`

### ISSUE THREAD

**Issue by kevlarr** [poteto/ember-changeset#182]
We have a scenario where our changeset isn't disposable - we allow the user to make changes, save/preview them, make more if they want to, etc...

One of the properties on the model being edited is a POJO - I know that changesets don't have great support for that yet, so I manually copy it and reassign it.

```
// "create" is a helper to avoid having to do lookupValidator every time
const changeset = create(parent, validations);
const pojoCopy = JSON.parse(JSON.stringify(parent.get('pojoProp')));

changeset.set('pojoProp', pojoCopy);
```

All well and good; can mutate the changegset pojo without any repercussion.

The issue, however, is when we `changeset.save()`... It sets its copied pojo back onto the parent object, meaning they now reference the same object - the situation we were trying to avoid in the first place - and changing the POJO via the form updates the underlying parent before we save it.

Is there any way that `.execute` could account for situations like this?
https://github.com/DockYard/ember-changeset/blob/master/addon/index.js#L172

It doesn't seem like it would be too terrible to do...
```
let content = get(this, CONTENT);
let changes = JSON.parse(JSON.stringify(get(this, CHANGES)));

setProperties(content, changes);
```
... because looking around the Issues right now, there is definitely some desire to better-support objects/arrays as props.

**Edit:** I know that the `JSON.parse(JSON.stringify(..))` combo doesn't copy functions, but what would the use case be for storing functions on data attributes?

**Comment by nucleartide** [comment]
@kevlarr I think this issue should be fixed with `v1.4.2-beta.0` of `ember-changeset`. Please try that out, and create another issue if you're still running into the same problem. :)
