### ISSUE TITLE
Saving a relationship-model doesn't actually trigger the API call

### ISSUE THREAD

**Issue by roberkules** [poteto/ember-changeset#199]
Let's say I have a Post model with an author relationship and I want to create an ember-changeset for the author only, I would do this on the controller/component:

```
authorChangeset: computed('post', function () {
  let author = this.get('post.author');
  return new Changeset(author);
})
```

but when I try to persist the author, calling `save` on the changeset doesn't trigger the API call.
looking at the source code I think I found the issue:

https://github.com/DockYard/ember-changeset/blob/master/addon/index.js#L192
```
if (typeOf(content.save) === 'function') {
  savePromise = content.save(options);
}
```

I noticed that `post.save` is a function, but `author.save` is undefined. *but* `author.get('save')` would actually work. so because it's undefined, the `savePromise` remains `resolve(this)` and does nothing.

so my question would be, is there a reason why not to change it to:  
`if (typeOf(get(content, "save")) === 'function') {`

(or is this not supposed to work anyways? bad pattern?)

---

update 1: actually might be a duplicate of #127 - but that's already fixed/closed and I'm on 1.3.0, so I shouldn't have that issue. (anyways, when creating the changeset the relationship is already resolved)

**Comment by roberkules** [comment]
```
authorChangeset: computed('post.author', function () {
  let author = this.get('post.author.content');
  return new Changeset(author);
})
```
actually it works when using `.content` for the changeset, is that the recommended way?

**Comment by Duder-onomy** [comment]
@roberkules I am running into this as well. 
If we have a non-blocking model hook, calling cave on the changeset will not call the persistence methods on the adapter. 
If you look at this twiddle: https://ember-twiddle.com/d4c526f3ad2782e785b8685a4e759543

**Comment by mhluska** [comment]
I'm experiencing this too. I guess this was never resolved?

**Comment by snewcomer** [comment]
@mhluska What version of ember-changeset are you on?  

FYI - sometime in October I plan on tackling some larger issues here and hopefully resolve the issue of getting at things via `content`.

**Comment by mhluska** [comment]
@snewcomer ember-changeset 1.5.0-beta.0 and ember-changeset-validations 1.2.11

**Comment by snewcomer** [comment]
@roberkules @mhluska Ok I think I solved this [here](https://github.com/poteto/ember-changeset/pull/333/files) (note this is targeting 2.0-beta branch).

**Comment by snewcomer** [comment]
We now unwrap the relationship and call save!  `3.6.1`

https://github.com/validated-changeset/validated-changeset/pull/71
