### ISSUE TITLE
Validate multiple (or all) fields on single change?

### ISSUE THREAD

**Issue by kevlarr** [poteto/ember-changeset#201]
We have a situation where at least one of several fields needs to be present, and we wrote custom validators that check other fields like this:

```
    minutes: function validateMinutes() {
        return (key, minutes, oldMinutes, changes, content) => {
            const hours = currentValue('hours', changes, content);

            // Coming from input, 0 will be "0"
            if (isEmptyOrZero(hours) && isEmptyOrZero(minutes)) {
                return 'Either minutes or hours must be provided';
            }

            return true;
        };
    },
    hours: ... same logic

```

If `minutes` are `null` or `"0"` and the user sets hours to `"0"`, it works fine - the `hours` field fails validation and we get the message just like we want. If someone then sets `minutes` to `"5"`, that field obviously validates, but the changeset is still invalid because `hours` wasn't re-validated.

Working around it now by putting a `change` handler on the inputs to manually trigger an update to the others, but could there be a cleaner way of making sure the entire changeset is valid on a single change?

**Comment by nucleartide** [comment]
That's interesting. I think if `Changeset` were a bit more extensible, you could instead write a computed property (CP) like `computed('hours', 'minutes', function() { /* ... */ })`, then validate that CP instead.

Leaving this open - great suggestion @kevlarr.

**Comment by snewcomer** [comment]
close #384
