### ISSUE TITLE
Validator function not triggered on call to validate

### ISSUE THREAD

**Issue by bkl1989** [poteto/ember-changeset#202]
I create a changeset like this
```
    let changeset = new Changeset({ name: null }, function (params) {
      debugger;
    });
```
Then, I try to validate the changeset like this: 

```
    changeset.validate().then(() => {
      debugger;
    });
```

The debugger in the validator function is never reached.  However, the debugger in the .then is reached.

However, if I leave code block 1 as is, and instead try to trigger the validator this way:

```
    changeset.set('name',changeset.get('name')) //name, at this point, is null
```

The debugger inside the validator function is reached. The "name" field is defined in both cases.

Is this an error? If not, what is the rationale for this behavior?

Thanks!

**Comment by kevlarr** [comment]
Running into this as well... Our use case creates an incomplete changeset for a form, but if a user submits the form without changing a single input, `validate()` does not mark the changeset as invalid.

**Comment by bkl1989** [comment]
@kevlarr Thanks a bunch. I was actually trying to use a map in the first place, and got discouraged, as I couldn't get it to work in a simple example like the first one I provided. So... `lookupValidator` generates the validator function for the map, and `validations` is the map? I don't get it - why are both of those arguments needed? Is there any way to generate the validator function without having to use their file / lookup system? I find it to be an unnecessary layer of indirection for small maps, but, meh... I've learned not to fight against the libraries I use.

**Comment by kevlarr** [comment]
@bkl1989 Yep, exactly - `validations` is the map that `lookupValidator` creates a function (from https://github.com/DockYard/ember-changeset-validations)... I agree that it's a little indirect, especially given that the docs are wrong and `new Changeset` needs that third argument. Honestly I'm not sure how to generate a function without using the lookup system, I'd tried that awhile ago and abandoned it for the same reason you said - learning not to fight the libraries haha..

**Comment by nucleartide** [comment]
The docs (https://github.com/DockYard/ember-changeset/tree/5d973b15387b5905506c1e3af2b72dcd72dca066#validate) do mention that the validation map is required, though I agree that it's easy to miss.

Making the validation map optional would be a good enhancement. If anyone's up for it, feel free to call dibs and open a PR. :)

**Comment by nucleartide** [comment]
Closing this issue since there hasn't been any activity. Please open a new issue if there are more questions!
