### ISSUE TITLE
How to reset/clear errors after an option is selected?

### ISSUE THREAD

**Issue by aandresrafael** [poteto/ember-changeset#204]
Hello,
Actually I'm using changeset and I faced up with a problem in my app. I have a new form and added validations, but some validations depend of what option is selected for type field. So IE. if i select the option1 for type field,  fields  description and detail are required, but if i select option2 fields description and detail is not required. I created a custom validation and this works, but the problem is with the UI. When I select option1 and description and details are empty it shows the errors correctly and the button save is disabled, then when I select option2 the errors are still there and button is still disabled. Not sure how to solve this in the UI. What i need is some way to clean errors after an option selected change. I tried to use  `changeset.rollback()` , but it clean the changes for other fields not related. Does exists something like `changeset.errors.clean`? thanks

**Comment by msalahz** [comment]
Hi @aandresrafael , I think [ember-changeset-conditional-validations](https://github.com/skaterdav85/ember-changeset-conditional-validations) can help you and provide conditional validation required in your case. If not, Can you share an ember-twiddle with a demo for your form and custom validation ?

**Comment by nucleartide** [comment]
@aandresrafael You shouldn't need to use `changeset.rollback()`, since choosing a new option (and changing the "type" field) will automatically re-run validation.

I second @msalahz though, an ember-twiddle would be helpful. :)

**Comment by nucleartide** [comment]
Going to start closing inactive issues – please open a new issue if you have any more questions!
