### ISSUE TITLE
changeset.rollback notifies listeners before updating values

### ISSUE THREAD

**Issue by asjongers** [poteto/ember-changeset#217]
Hi,
I have an application with an observer checking the changes made to a changeset field. 
However, when I rollback the changes made and my observer fires, the value is still the old one.
If I delay the code checking the value by placing it in an Ember.run.next then I do have access to the correct rolledback value.

I have created [a twiddle](https://ember-twiddle.com/63299c8032a3dcdcfb231c5a0fdfe4d7?openFiles=templates.application.hbs%2C) to mimic this behavior, just change the firstName, rollback and then you'll see the immediate & delayed value appear.

From this behavior and [what I've seen in the ember-changeset code](https://github.com/poteto/ember-changeset/blob/dcc28a6383577a0674b5eef420819a05c8d5a886/addon/index.js#L246) so far, I suspect that the notifications are sent before the values are actually modified.

**Comment by nucleartide** [comment]
Hey @asjongers, thanks and sorry for the late reply.

I'm a little busy with Ludum Dare and work deadlines atm, but I'll take a look at this for the upcoming bugfix release. Hope that's okay with you!
