### ISSUE TITLE
Nested error should not report error for parent object

### ISSUE THREAD

**Issue by nucleartide** [poteto/ember-changeset#220]
https://github.com/poteto/ember-changeset/blob/cae85fd49eef957e8b7908252860b6be56f3a04d/addon/index.js#L621

This breaks the canonical ember-twiddle example.

Will need to devise a test case. Could change it to `key in errors && 'value' in errors[key]`.

**Comment by BillyRayPreachersSon** [comment]
While the error you give above is in the `_valueFor` method, I see errors with the same `hasOwnProperty` call in the [`_allKeys`](https://github.com/poteto/ember-changeset/blob/cae85fd49eef957e8b7908252860b6be56f3a04d/addon/index.js#L474) method (with no changes in my code except  revving `ember-changeset` to `1.4.1` and `ember-changeset-validations` to `1.2.9`):
```
_allKeys(object, keys = [], scope = '') {
    for (let key in object) {
        if (!object.hasOwnProperty(key)) {
```

In that instance, `object` appears to be the following:
```
{
    clearNext: ƒ (id),
    clearTimeout: ƒ (id),
    next: ƒ (fn),
    now: ƒ (),
    setTimeout: ƒ (fn, ms)
}
```

Searching around, the only similar thing I can find is in a library called [BackburnerJS](https://github.com/BackburnerJS/backburner.js/blob/master/lib/index.ts#L41), and this ties in with what I'm seeing the value of `scope` set to (`"response.changeset._content.store._backburner._platform."`).

What I've no idea about is how `object` (which returns `'object'` for a call to `typeof(object)` doesn't have the `hasOwnProperty` method from `Object.prototype`. Having said that, `object.constructor` shows `undefined`, so I guess that the object was created using some sort of dark arts.

If you'd like me to create a separate issue for this, I'm happy to do so, but my guess is that they're related somehow.

**Comment by nucleartide** [comment]
@BillyRayPreachersSon Thanks for reporting - if you'd like you can revert back to the old `1.3.0` release for now. Will be working on these bugs after work this week.

**Comment by webark** [comment]
@nucleartide I don’t completely understand the error you are having. I can work on this in the next couple of days though. Could you expand on “report error for parent object”?

**Comment by nucleartide** [comment]
@webark Yep! So if you have a change for `org.usa.ny`, you'll have the `org` property, but no `org.value` property. Thus, the `get` on the subsequent line will fail:

https://github.com/poteto/ember-changeset/blob/cae85fd49eef957e8b7908252860b6be56f3a04d/addon/index.js#L621-L622

If you don't mind, I'd like to work on this tonight in order to get a bugfix release out very soon. D: Will let you know if I can't get to it though!

**Comment by webark** [comment]
@nucleartide sure thing! And ya. Maybe I'm interpreting things wrong, but there shouldn't be an `org.value` property in the errors object, since `org` doesn't have an error, only `org.usa.ny` has the error. When you set up your validations you have to add them to the inner object. like https://github.com/poteto/ember-changeset/blob/master/tests/unit/changeset-test.js#L38-L44

**Comment by BillyRayPreachersSon** [comment]
Should I move my problem (that i thought was related) to a new issue?

**Comment by nucleartide** [comment]
@BillyRayPreachersSon Oh whoops! Yes please, that would be great.
