### ISSUE TITLE
Memory leak in Relay class

### ISSUE THREAD

**Issue by nucleartide** [poteto/ember-changeset#221]
https://github.com/poteto/ember-changeset/blob/cae85fd49eef957e8b7908252860b6be56f3a04d/addon/-private/relay.js#L20-L21

This generates a lot of dupes, especially when spamming a single `<input>`. Maybe change to an object?

**Comment by webark** [comment]
@nucleartide i can work on this sometime in the next couple of days if you (or someone else) can’t get to it.
