### ISSUE TITLE
Errors for nested keys don't go away once shown

### ISSUE THREAD

**Issue by nucleartide** [poteto/ember-changeset#224]
Trying to extend @poteto's original twiddle but there are still some issues. Need to take another look before publishing a patch release.

**Comment by webark** [comment]
@nucleartide I could work on this tomorrow if you can pate the twiddle that you say, or explain a repo steps a little more.

**Comment by nucleartide** [comment]
@webark I added a failing test case, lemme see if I can figure it out in the next half hour. If not, feel free to take this. :)

**Comment by nucleartide** [comment]
@webark Seems like the test fails on earlier Ember versions, do you want to take a look tomorrow? I think that's enough for me today haha.

Aiming for a release (and official announcement) early next week.
