### ISSUE TITLE
Since nested keys work, I'm getting an error in the _allKeys method: object.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by BillyRayPreachersSon** [poteto/ember-changeset#225]
After revving `ember-changeset` to `1.4.1` and `ember-changeset-validations` to `1.2.9` (from `1.2.0` and `1.2.4` respectively), with no other changes in my code, I'm getting an error with the `hasOwnProperty` call in the [`_allKeys`](https://github.com/poteto/ember-changeset/blob/cae85fd49eef957e8b7908252860b6be56f3a04d/addon/index.js#L474) method of `ember-changeset/addon/index.js` when trying to validate & save my model:
```
_allKeys(object, keys = [], scope = '') {
    for (let key in object) {
        if (!object.hasOwnProperty(key)) {
```

Debugging the error shows `object` to be the following:
```
{
    clearNext: ƒ (id),
    clearTimeout: ƒ (id),
    next: ƒ (fn),
    now: ƒ (),
    setTimeout: ƒ (fn, ms)
}
```

Searching around, the only similarly structured object I can find is in a library called [BackburnerJS](https://github.com/BackburnerJS/backburner.js/blob/master/lib/index.ts#L68), and this ties in with what I'm seeing the value of `scope` set to (`"response.changeset._content.store._backburner._platform."`).

What I've no idea about is how `object` — which returns `'object'` for a call to `typeof(object)` — doesn't have the `hasOwnProperty` method from `Object.prototype`. Having said that, `object.constructor` shows `undefined`, so I guess that the object was created using some sort of dark arts.

I thought this might have been related to [Issue 220](https://github.com/poteto/ember-changeset/issues/220), but possibly not.

Would it cause a lot of problems to change `if (!object.hasOwnProperty(key)) {` to `if (!(key in object)) {`?

I see there are a few other uses of `.hasOwnProperty`, but am not sure as to whether they would need changing as well.

**Comment by nucleartide** [comment]
@BillyRayPreachersSon Thanks for opening this! I appreciate the detail.

> What I've no idea about is how object — which returns 'object' for a call to typeof(object) — doesn't have the hasOwnProperty method from Object.prototype. Having said that, object.constructor shows undefined, so I guess that the object was created using some sort of dark arts.

Hmm, it sounds like `object` is an `Object.create(null)`.

> Would it cause a lot of problems to change `if (!object.hasOwnProperty(key)) {` to `if (!(key in object)) {`?

I think the `.hasOwnProperty` check is to avoid hitting prototype methods, but we should switch this over to `Object.keys()` anyway, which is more robust.

If anyone has the time (it's kinda late for me right now 😆) and wants to contribute, could you call dibs by posting here? To fix this issue, I'd like unit tests + fixes for the `_allKeys` method. (Yeah `_allKeys` is private, but we'll let that slide for now.)

Otherwise, I can also call dibs later this week.

**Comment by webark** [comment]
@nucleartide i can pick it up today.

**Comment by nucleartide** [comment]
@webark awesome! We can also pull the allKeys method into utils, since it doesn’t depend on instance state.

**Comment by webark** [comment]
ya. that’s what i was planning on doing after a quick sweep to see if it exists anywhere in the world.

**Comment by m-nagy** [comment]
When could we have this fix into release?

**Comment by nucleartide** [comment]
@m-nagy There are a few bugs (https://github.com/poteto/ember-changeset/milestone/3) I'd like to resolve before releasing a patch.

For now, I'd recommend reverting to the pre-nested keys versions of ember-changeset and ember-changeset-validations:

```json
{
  "ember-changeset": "1.3.0",
  "ember-changeset-validations": "1.2.8"
}
```

Ideally, you should not be using nested keys until there is documented support.
