### ISSUE TITLE
QA for nested keys release (~1.4.0)

### ISSUE THREAD

**Issue by nucleartide** [poteto/ember-changeset#233]
For all issues, please submit a PR whose initial commit is a **failing test** (as reported by Travis). Subsequent commits should fix the initial failing test.

15. [x] @krishandley `_hasOwnNestedProperty` does not depend on instance state, let's pull this into `utils`.
14. [x] @nucleartide Audit `_setProperty` for possible nested keys bugs.
5. [x] (no tests needed here) Update the JSDoc for `_validate`. `_validate` can also return a Promise.
13. [ ] @nucleartide More detailed JSDoc for `_valueFor`. (What does `plainValue` do?)
16. [ ] @krishandley  `_rollbackKeys` should use the new `leafKey` util. We should also de-dupe the keys here.
10. [ ] @nucleartide `execute` should use `includes` util. See: https://github.com/poteto/ember-changeset/blob/709be66ae6aae9a0a5c1dc21136da2a51c2f2970/addon/index.js#L206
11. [ ] @nucleartide https://github.com/poteto/ember-changeset/issues/229
1. [ ] Ensure `_deleteKey` notifies all properties up the key chain. For example, `_deleteKey(someObj, 'foo.bar.baz')` should notify `foo`, `foo.bar`, and `foo.bar.baz`.
4. [ ] `_setIsValidating` won't work with nested keys. We should use `deepSet` here.
    - Related, `isValidating` should use the new `leafKeys` util.
6. [ ] `cast` may not work with nested keys – write some tests for this.
7. [ ] `pushErrors` will fail if a nested key is passed in. Might need to use `deepSet` here.
8. [ ] `validate` should accept both types of validation maps. Example:
    - `{ 'foo.bar.baz': someValidationFn }`
    - `{ foo: { bar: { baz: someValidationFn } } }`
9. [ ] Ensure `merge` works with nested keys.
12. [ ] Investigate last 2 commits for https://github.com/poteto/ember-changeset/pull/206

**Comment by krishandley** [comment]
Will help if I can!

**Comment by nucleartide** [comment]
@krishandley @webark + anyone who might be reading, I've listed the issues in the original post. Please chip in if you'd like!

**Comment by webark** [comment]
@nucleartide i’ll jump on some of these tomorrow.. thanks!

**Comment by krishandley** [comment]
I'll take an easy one to start with extracting _hasOwnNestedProperty

**Comment by krishandley** [comment]
I can do take the _rollbackKeys item as well, I added that method it after all 😄

**Comment by krishandley** [comment]
Added PR for #229

**Comment by nucleartide** [comment]
@krishandley Thanks for the PRs! Sorry for not getting back to you earlier – I'll try to review them when I get a chance today.

**Comment by krishandley** [comment]
@nucleartide no problem, take your time 👍

**Comment by krishandley** [comment]
Looking into _setIsValidating with nested keys - I opened a PR for an issue which needed fixing first #247

**Comment by nucleartide** [comment]
@krishandley @webark I'm going to close this issue in favor of making individual issues for each task. Also, I'd like to address https://github.com/poteto/ember-changeset/pull/247#issuecomment-351598545 before allowing other contributions (so as not to duplicate effort nor add PR review overhead).

So please hold off for now 🙏  will let you know once the project management side of things is more organized.
