### ISSUE TITLE
Add support for dynamic validation field filtering

### ISSUE THREAD

**Issue by erichonkanen** [poteto/ember-changeset#263]
Problem:

Form has a section that can be toggled in the UI by the user by clicking a button. If this section is toggled, we want to also include it's fields during validation, if it is not toggled, we do not want to include it's fields during validation (conditional validation). The property used to toggle the form section is in the parent scope (component).

How can we conditionally validate these fields? Answer, there is not currently a clean way to do this

![image](https://i.imgur.com/nOhylaI.jpg)
![image](https://i.imgur.com/xZggFJ0.jpg)

After going down a few paths trying to work with existing configuration, I looked at the source and realized it could use a few small enhancements to open up the ability to handle this situation in a clean manner. There does exist [ember-changeset-conditional-validations](https://github.com/skaterdav85/ember-changeset-conditional-validations) but it only works for properties that are part of the changeset/model and not with parent scope. 

Opening this Issue for discussion with links to WIP/rough working example of the updates (based on develop/nested-keys branch).

https://github.com/erichonkanen/ember-changeset/pull/1
https://github.com/erichonkanen/ember-changeset-validations/pull/1

Suggestions:
- Generate array of validation key names from the validationMap during init.
- Expose `changeset._validationKeys` for developer to optionally manipulate validation keys.
- Expose `changeset._validationMap` for developer to optionally manipulate validation map.
- Filter through the validation keys prior to validating a field. (this could in theory be done on the `ember-changeset` side instead of passing it through to the validator).
- Accept an optional `validationKeysFn` function that is the hook where a developer can dynamically filter the keys that should be used for validation (example below).
- No longer redundantly pass the `validationMap` into `lookupValidator` during changeset construction.

Example:
```
    {{#changeset-form
        changeset
        isRunning=_submit.isRunning
        name="customer-profile"
        as |form|
    }}
    ...
            {{#form.fieldset name='password'}}
                {{#if isPasswordVisible}}
                    {{form.input 'current_password' type='password'}}
                    {{form.input 'password' type='password'}}
                    {{form.input 'confirm_password' type='password'}}
                {{/if}}

                {{form.button.button
                    action=(toggle 'isPasswordVisible' this)
                    buttonText=(if isPasswordVisible 'close edit password' 'edit password')
                }}
            {{/form.fieldset}}
```
```
    init() {
        this._super(...arguments);

        this.changeset = new Changeset(
            get(this, 'model'),
            lookupValidator(),
            CustomerProfileValidations,
            { validationKeyFn: this.updateValidationKeys.bind(this) }
        );
    },

    updateValidationKeys(keys = []) {
        if (!get(this, 'isPasswordVisible')) {
            return keys.removeObjects([
                'confirm_password',
                'current_password',
                'password'
            ]);
        }
        return keys;
    }
```

Stopping here but open to feedback/discussion. I've encountered this situation more than once now and it'd be ideal if there were an easy/intuitive way to handle it.

**Comment by nucleartide** [comment]
@erichonkanen Thanks for opening the issue. As discussed on Slack, I still think iterating through your validation map, and wrapping each validator with another function bound to `this` is the way to go. It sounds like you had trouble doing that though? I'll write up an example if I'm not busy.

While this may be a good idea, at this point I'd like to keep the `ember-changeset` and `ember-changeset-validations` APIs as stable as possible – mostly to cut down on maintenance burden.

**Comment by erichonkanen** [comment]
@nucleartide certainly open to viewing your implementation but as far as I tried it does not work. Additionally it is not an intuitive solution to wrap each validator function with a bound contextual function. One thing I discovered is that the current implementation of passing the validationMap into the `lookupValidator` function is unnecessary as you can simply pass it through the `validate()` method thus avoiding the redundant use of it during `new Changeset()`. Adding the concept of `validationKeys` with an optional hook into it seems like a sensible solution...

**Comment by nucleartide** [comment]
@erichonkanen To expand on why I'm somewhat against this: a `Changeset` is a set of valid changes to be applied onto any Object. This implies that the validation rules are static.

To illustrate, take a look at how `Ecto.Changeset` defines a changeset:

```ex
defmodule User do
  use Ecto.Schema
  import Ecto.Changeset

  schema "users" do
    field :name
    field :email
    field :age, :integer
  end

  def changeset(user, params \\ %{}) do
    user
    |> cast(params, [:name, :email, :age])
    |> validate_required([:name, :email])
    |> validate_format(:email, ~r/@/)
    |> validate_inclusion(:age, 18..100)
    |> unique_constraint(:email)
  end
end
```

Note that the validations are baked into the definition. There is nothing about them that is dynamic; the dynamic part is contained _inside_ the `validate` functions.

This does need docs though – I will keep this in mind.

**Comment by erichonkanen** [comment]
I see what you're saying but I guess I was just looking at the validation map itself as having a dynamic component... I guess the real problem is how to enable conditionally validating a field in a way that is somewhat easy to implement/understand. I know I also mentioned another possibility could be optionally allowing computed's for the validation fields e.g.:
```
    email: validateFormat({ type: 'email' }),

    password: computed('context.isPasswordVisible', function() { ... })
```
but it would still require somehow passing the context into it to get the behavior I was going after. For now I was going to just create a separate form for the password and toggle that as needed, but I'm almost certain I've run into this before and it seems like a use case that would be fairly common with forms these days.

Open to discussing further to think of other solutions though or if you think it's already supported via the validator's and just needs documentation then I'll check that out.

**Comment by erichonkanen** [comment]
btw I don't think it's possible inside the validator unless there is some clever way to pass the parent scope into it(?)

`app/validations/customer-profile.js`
```
export default {
    address_line1: [
        validatePresence(true)
    ],
    current_password: [
        validatePassword().bind(this)
    ],
```
`this` is the validations file and not the parent Component
