### ISSUE TITLE
Calling `set` on changeset for a `belongsTo` is not working in beta [1.4.2 beta]

### ISSUE THREAD

**Issue by erichonkanen** [poteto/ember-changeset#273]
In the following code, `changeset.get('payment_gateway.id') === undefined`, I also tried `changeset.set('payment_gateway', <paymentgateway object>)`

```
     _submit: task(function* (changeset) {
        // handle case of 1 shared gateway by auto-selecting it.
        if (get(this, 'onlyOneSharedGateway')) {
            set(changeset, 'payment_gateway', get(this, 'paymentGateways.firstObject'));
        }
```

**Comment by nucleartide** [comment]
Could you open another issue and add more detail? (I've added an issue template.) Not sure what's wrong here.
