### ISSUE TITLE
Saving form with `belongsTo` throws error [1.4.2 beta]

### ISSUE THREAD

**Issue by erichonkanen** [poteto/ember-changeset#274]
I am seeing the following when I call `changeset.save()` on my ember-data backed form which has a `belongsTo`:

```
Cannot delegate set('first_name', e) to the 'content' property of object proxy <DS.PromiseObject:ember2187>: its 'content' is undefined.
```

Here is the model:
```
export default Model.extend({
    number: attr('string'),
    expiration_month: attr('number'),
    expiration_year: attr('number'),
    ccv: attr(),
    billing_address: belongsTo('billing-address'),
    payment_gateway: belongsTo('payment-gateway'),
```

**Comment by nucleartide** [comment]
Thanks for opening these issues @erichonkanen, I would like more detail though. Please fill out the issue template if you get the time. An Ember Twiddle or repo reproduction would be ideal.

**Comment by erichonkanen** [comment]
ok I will, but the tldr is you can't `set(changeset, <belongsToField>)` directly
