### ISSUE TITLE
Investigate redux-form

### ISSUE THREAD

**Issue by nucleartide** [poteto/ember-changeset#275]
https://redux-form.com/6.6.3/docs/gettingstarted.md/

---

EDIT

Also, this has been trending lately: https://github.com/thejameskyle/unstated

Without the Redux baggage, it looks more in line with the Ember way of doing things... might be worth a look too.

**Comment by erichonkanen** [comment]
what's use case?

**Comment by nucleartide** [comment]
It just seems like really similar territory. Apparently redux-form is the form lib of choice in the React ecosystem. I figure it'd help to study the lib with the most mindshare. There is also [formik](https://github.com/jaredpalmer/formik), which looks interesting.

(FWIW, I write React at work. Shh don't tell anyone :D)

**Comment by erichonkanen** [comment]
haha nice, how do you like it? I wouldn't mind dipping my toes in the React water at some point but haven't really had a reason to so far.. will check out the lib
