### ISSUE TITLE
Feature Request: A way to remove errors without rolling back

### ISSUE THREAD

**Issue by erichonkanen** [poteto/ember-changeset#282]
In our form component and app we have a concept of `non_field_errors` which get returned from the api (default django-rest-framework behavior). These errors are "form-level" and not tied to a specific field.

To keep things simple we use our changeset form to display these if they occur by doing something like:
```
        try {
            yield bankcard.save();
        } catch (err) {
            err.errors.forEach(({ attribute, message }) => {
                changeset.pushErrors(attribute, message[0]);
            });
            return undefined;
        }
```
which if `err` === `non_field_errors`, our form template will render at the top of the form like:
```
    {{cool-form/error changeset "non_field_errors"}}
```
The problem is if a user submits and receives a non_field_error, we have to then handle clearing just that one specific error before they can submit again. While this is easy to do, to delete just that specific error with no related input attached we have to do `delete changeset._errors.non_field_errors`

Proposal: Can we add a public interface to remove a single error without relying on private properties?

e.g. `changeset.removeError('non_field_errors')` or `changeset.clearError('non_field_errors')`

OR just a public way to clear all errors e.g. `changeset.clearErrors()` without rolling the form back

**Comment by nucleartide** [comment]
Thanks for the detailed writeup @erichonkanen, this sounds reasonable to me.

My only concern is that I don't remember (off the top of my head) if `changes` and `errors` are mutually exclusive. Here's what I mean:

```js
const c = new Changeset(...);
c.set('phoneNumber', '123-123-1234'); // valid, internal changes map has 'phoneNumber'
c.set('phoneNumber', 'asdfhjkl'); // invalid, internal errors map has 'phoneNumber'
// but does the internal changes map still have 'phoneNumber'?
```

If `changes` and `errors` are mutually exclusive, then feel free to open a PR for this! Maybe something like `changeset.rollback({ onlyErrors: true });`?

**Comment by snewcomer** [comment]
I'll try to get this one done this week...

**Comment by erichonkanen** [comment]
@snewcomer I hadn't seen those before, let me try those out and get back to you.. but basically we handle form-level errors in our changeset form by doing `changeset.pushError({ non_field_error: <error> })` which displays the error as part of our normal form component machinery, the problem is we now need to clear that non_field_error before user hits submit again, but there wasn't a way to do it w/o resetting the form

**Comment by snewcomer** [comment]
@erichonkanen Yeah it seems like `rollbackInvalid` is close to what you want.  But perhaps want to rollback a specific key but keep the changes, correct?  In which case, we need to add a bit more flavor to `rollbackInvalid`.

**Comment by hornetnz** [comment]
> ...the problem is we now need to clear that non_field_error before user hits submit again, but there wasn't a way to do it w/o resetting the form (we ended up just putting a `delete changeset._errors.non_field_error` before submit is called)

@erichonkanen - Were you doing a notifyProperty or something else on changeset to get isValid to recompute? I did a removeObject on the error I manually pushed in (leaving an empty array), but changeset.isValid still resolves false.

**Comment by snewcomer** [comment]
@hornetnz If you don't mind, try 2.0 and lmk if that fixes the issues you are seeing.  Otherwise, definitely open to a PR!

**Comment by erichonkanen** [comment]
@hornetnz I think I actually had to do something like `changeset.set('non_field_errors', null)` to get it to clear, but I'd have to dig that up again :) also just tried the latest 3.0 and seems to be working finally so thanks @snewcomer :)

**Comment by hornetnz** [comment]
Ok, thanks for the reply @erichonkanen! I'm unable to upgrade currently because we have some monkey-patches in this changeset to work with our unique data structure.

**Comment by snewcomer** [comment]
@hornetnz or @erichonkanen is there an opportunity to extend ember-changeset to enable some of these features?  Do you mind sharing those monkey patches?  Looking at improving the internals.

**Comment by erichonkanen** [comment]
@snewcomer I think in the latest version it's no longer necessary since rollbackProperty was added

**Comment by snewcomer** [comment]
Cool.  Sry what do you mean...

> latest version it's no longer necessary

**Comment by erichonkanen** [comment]
yeah, the monkey patch I was referencing was for 1.3, no longer necessary
