### ISSUE TITLE
Discussion of ember-changeset's plugin mechanism

### ISSUE THREAD

**Issue by nucleartide** [poteto/ember-changeset#285]
Based off of the discussion in https://github.com/poteto/ember-deep-set/pull/10, I've been thinking about how to make maintenance of `ember-changeset`'s plugin ecosystem less painful. I think it helps to start with a few diagrams.

This is `ember-changeset`'s ecosystem as it looks today, with arrows representing `"dependencies"` in `package.json`.

![changeset_graph](https://user-images.githubusercontent.com/914228/36067121-ea8875e0-0e84-11e8-896f-8bf17c1d2c42.png)

In this current model, updating `ember-deep-set` forces updates to every addon downstream. (The graph should really have arrows pointing up, but you should get the idea.) This makes maintenance kinda tedious, as seen in https://github.com/poteto/ember-deep-set/pull/10#issuecomment-363286370.

Also, there are probably other `ember-changeset` plugins out there that hard-depend on a specific version of `ember-changeset`. When a user installs multiple plugins in addition to `ember-changeset`, it's hard to figure out the exact versions of `ember-changeset` / `ember-changeset-validations` loaded by `ember-cli`.

A better model might look like this:

![changeset_graph2](https://user-images.githubusercontent.com/914228/36067198-8d5ca75e-0e86-11e8-95ca-a0fd558ba8b0.png)

In this model, any `ember-changeset` plugin _peer depends_ on `ember-changeset`. The npm blog [goes into more detail](https://nodejs.org/en/blog/npm/peer-dependencies/), but the gist of it is that `ember-changeset` plugins shouldn't need to directly import `ember-changeset` to modify it. We should be providing an extension mechanism directly in `ember-changeset`, and allow users to "plug" code in themselves.

The best example of plugins would be [Express middleware](https://expressjs.com/en/guide/using-middleware.html). https://github.com/poteto/ember-changeset/issues/178 is another use case to think about.

Having glanced at https://github.com/ember-cli/rfcs/pull/112, I think all of this might be wishful thinking if `ember-cli` doesn't support `peerDependencies`. Just posting my thoughts on the topic though – **if anyone has ideas or is interested in implementing a solution, please post here!**

**Comment by snewcomer** [comment]
https://github.com/validated-changeset/validated-changeset
