### ISSUE TITLE
No validation with complex model attributes

### ISSUE THREAD

**Issue by danielrestrepo** [poteto/ember-changeset#290]
Hi, I know this has been largely discussed on other issues but I can't manage to get proper support for nested keys validation. Not long ago I had it working like this in a validator:

```js
['birthPlace.country']: [
    validatePresence(true),
    validateLength({min: 5})
  ]
```
Also tried with:
```js
'birthPlace.country': [
    validatePresence(true),
    validateLength({min: 5})
  ]
```
But in any case the validation results in having it `undefined`

## Version
1.4.1 and v1.5.0-beta.0

Very much appreciate if I you can provide an example

**Comment by snewcomer** [comment]
See this PR - https://github.com/poteto/ember-changeset-validations/pull/222 in the new 3.0 series!

Thanks for the issue and lmk if something doesn't work
