### ISSUE TITLE
long-running promise validations cause UI delays, unpredictable results

### ISSUE THREAD

**Issue by bgentry** [poteto/ember-changeset#297]
## Version

v1.5.0-beta.0

## Test Case

I believe I've uncovered a flaw in the design of this addon around how it handles promise-based validations. Take the following `<input >` wired up to a changeset:

```hbs
<input value={{changeset.email}} oninput={{action (mut changeset.email) value="target.value"}}>
```

Simple scenario. Now imagine you're validating that email against a remote server, i.e. the promise will take awhile and the duration will of course be variable.

When you set a property on the changeset, it calls [its `_validateAndSet` method](https://github.com/poteto/ember-changeset/blob/353d0e5822efca3104a2b147e47608bc0176e440/addon/index.js#L574-L604). For validations that return promises, the following happens:

1. User calls `changeset.set('email', "john@example.com")`
2. Validation returns a promise, which can be as simple as a timeout / sleep to illustrate this issue
3. The promise is resolved by `_validateAndSet`, anywhere from a few ms to several seconds
4. The validation result is then passed to `_setProperty`
5. `_setProperty` actually sets the new value on the changeset, along with any validation error

The entire time this is happening, the input continues to render with the old value because `changeset.email` has not actually changed yet (not until the end of step 5). So I could type `j` and then continue typing the rest of the email, but the input will appear to be frozen. Once step 5 finishes (which could be hundreds or thousands of ms), then the field actually updates.

This gets even worse if you have multiple validation requests in-flight, which will probably happen even with debouncing. You're not actually guaranteed that any of these promises will resolve in the same order they were started, so you can potentially get the `joh` promise resolving before the `jo` promise, in which case `changeset.email` will ultimately be set to `jo`.

I hope I'm seriously misunderstanding something here because it doesn't seem like it will be easy to fix 😕

**Comment by bgentry** [comment]
I think I have a promising lead on solving this! My solution involves a couple of key changes:

* rather than `_validateAndSet`, do `_setAndValidate`. Immediately set the new value on `_changes` before starting the validation.
* Validate using ember-concurrency, ensuring that only one validation of each property is running at a time. I created a `PropertyValidator` object type for this:

```js
const PropertyValidator = EmberObject.extend({
  key: null,
  validator() {},

  isRunning: readOnly("validate.isRunning"),

  validate: task(function*(changeset, newValue, oldValue, changes, content) {
    let result = yield this.validator({
      key: this.key,
      newValue,
      oldValue,
      changes,
      content,
    });
    let isValid =
      result === true ||
      (isArray(result) && result.length === 1 && result[0] === true);

    // Error case.
    if (!isValid) {
      changeset.addError(this.key, { value: newValue, validation: result });
    }
  }).restartable(),
});
```

Then on the changeset itself, at the end of init I set up a map of `PropertyValidator` objects for each property in the validation map:

```js
  _initPropertyValidators() {
    let c = this;
    let validator = get(this, VALIDATOR);
    Object.keys(this[VALIDATION_MAP]).forEach(key => {
      c[PROPERTY_VALIDATORS][key] = PropertyValidator.create({
        key,
        validator,
      });
    });
  },
```

The difference is dramatic. Here's an example using the current ember-changeset code when Chrome simulating a Slow 3G network:

![changeset-without-ec](https://user-images.githubusercontent.com/114033/40709034-d73f80bc-63a9-11e8-95b1-8ac61fcc36e7.gif)

Notice how the input jumps around like crazy as I type fast (once the first validation promises start to resolve).

Now, the new solution with ember-concurrency as described above:

![changeset-with-ec](https://user-images.githubusercontent.com/114033/40709078-f4e9fb6a-63a9-11e8-93d3-fa8f7e3696c9.gif)

Everything works smoothly.

I could attempt to turn this into a PR, but I'm concerned that won't be accepted given the scope of the change and the number of open issues & PRs on this repo. Otherwise I could create ember-concurrency-changeset 😄

Thoughts?

**Comment by sukima** [comment]
Although it could be argued that the setting being delayed till after validations is a bug (and I agree) there is a simpler work around which is to set the changeset's config to `skipValidations` this way the input changes immediately. You then attach an `onInput` or `onChange` event which performs a restartable task that calls the changeset's `validate()` method.

**Comment by bgentry** [comment]
I've been putting together a fix for this, and I realized I'm confused about a core principle of ember-changeset. As stated in the readme:

> Each change is tested against an optional validation, and if valid, the change is stored and applied when executed.

Or, restated by [this test](https://github.com/poteto/ember-changeset/blob/353d0e5822efca3104a2b147e47608bc0176e440/tests/unit/changeset-test.js#L334-L351)

> ```js
> test('#set does not add a change if invalid', function(assert) {
> ```

Also from the readme:

> `ember-changeset` only allows valid changes to be set, so your Objects will never become invalid (assuming you have 100% validation coverage).

Now, that last part makes perfect sense. I don't want any invalid changes to apply to my objects. However, I don't understand why that means that it shouldn't be marked as a `change` on the changeset even if it is invalid. Is it because people `execute` without first waiting for a successful validation?

IMO the changeset always needs to reflect the values that I've set on it. It might simplify the code considerably if that were the case. What am I missing?

The second question I have is around the `validationMap` input. I've never actually used this addon without it, so I'm curious how common that is. My solution above was based on having that map available for creating the `PropertyValidator` / ember-concurrency objects when the changeset is initialized. Maybe it could be adapted to work with keys that aren't known at that time.

Would love to hear some insight from maintainers on this. At the moment I'm more leaning towards having a separate addon for given that it might be hard to maintain existing behaviors / expectations while still fixing this larger bug around promise validations.

**Comment by snewcomer** [comment]
@bgentry I would also consider this a bug.  Generally, I think 1.5 should fix this and setting relationships.  Before `execute`ing those changes, one can/should to call `validate()` and this could be documented.  Something like:

```
    changeset.validate();
    if (changeset.get('isValid')) {
      changeset.execute();
    }
```

On your point, I think fundamentally `changes` should represent all changes, whether valid or not.  Anything upstream that happens simply throws out invalid changes before applying it to the underlying model. 

I'd be in favor of making this change (whether you or I or somebody else tackles it) 👍

**Comment by sukima** [comment]
> `ember-changeset` only allows valid changes to be set, so your Objects will never become invalid (assuming you have 100% validation coverage).

There is a major problem with this statement! How can the state of the UI be represented in the changeset if it never allows invalid input?

```hbs
{{input value=changeset.validatedText}}
```

In this situation it would be impossible to enter text if the changeset refuses to set invalid data, would it not? I'm not sure how this would work in ember.

I do see not applying the changes (`execute()`) if the changeset is invalid, that makes sense. But to prevent `changeset.set()` seems very odd and introduces in inconsistency on how Ember handles EmberObjects and how changesets react.

**Comment by snewcomer** [comment]
@bgentry Below is pt. 1 to fixing this issue.  Lmk what you think!  Will be testing out in my app tonight.  Looking at the promise stuff now as well.

@sukima I think it only works with one way inputs `<input`, not two way.  So the example you posted I *think* won't work.  But with `<input`, it will.

https://github.com/poteto/ember-changeset/pull/303

**Comment by snewcomer** [comment]
Note I don't think #303 solves the "pausing" issue in your case.  I do a similar thing [here](https://github.com/snewcomer/ember-validated-input/blob/master/addon/components/validated-input.js#L48) so perhaps we either need an "Tips and Tricks" section or, like you mentioned an addon....

https://github.com/snewcomer/ember-validated-input

**Comment by snewcomer** [comment]
@sukima @bgentry Invalid changes should now show up in `CHANGES` as of 1.5.0-beta.2!  Might be worthwhile to investigate the async issues here before 1.5 proper.  

I personally use `onblur` to do validations, but I can totally see the use case for `oninput`.

https://github.com/poteto/ember-changeset#tips-and-tricks

**Comment by snewcomer** [comment]
Closing for now!
