### ISSUE TITLE
Call for maintainers & an apology

### ISSUE THREAD

**Issue by nucleartide** [poteto/ember-changeset#299]
Hey folks,

Sorry for being unresponsive over the past couple months. I wish I could say it was because of work, but to be honest I just haven’t prioritized maintaining this addon (and related addons).

So, I’d like to step down as a maintainer. @poteto and @Dhaulagiri (I believe you’re also a collaborator), would you be open to finding more maintainers?

While `ember-changeset` is mostly usable on 1.3.0 (prior to the nested keys updates), the newer versions remain buggy, and cause problems for new `ember-changeset` users. I’m so sorry about this. @poteto invested a lot of time in this addon and [many people in the community](https://github.com/poteto/ember-changeset/pull/140) chipped in for the nested keys updates, so I’d like to hold myself accountable and fix any remaining bugs.

At the same time, I feel like there are a lot of competing solutions that make it a drag to work on this addon:

- [ember-cp-validations](https://github.com/offirgolan/ember-cp-validations)
- [Orbit](https://github.com/orbitjs/orbit#standard-data-sources)
- [ember-buffered-proxy](https://github.com/yapplabs/ember-buffered-proxy) and [ember-validated-form-buffer](https://www.npmjs.com/package/ember-validated-form-buffer)

It’d be nice to consolidate efforts. _Ideally_, Ember Data would have built-in changesets of some sort. Maybe it’s most worthwhile to just contribute to Ember Data. Or as @poteto suggests, see if we can implement `ember-changeset`’s API using `validated-proxy`, which is the more general version of this addon.

Assuming @poteto and @Dhaulagiri are okay with this – is anyone interested in taking over `ember-changeset` maintenance?

**Comment by Dhaulagiri** [comment]
I was only recently added as a maintainer and I don't have all that much time to contribute new work myself unfortunately, but my main goal is to ensure that the addon is in a consistent working state. 👍  to getting more folks involved who are interested.

**Comment by snewcomer** [comment]
@Dhaulagiri Also if you would be interested in pairing on setting relationships bug, it would be great to work with someone on it.  Currently seeing if I can flush out a solution, but might take some time...

**Comment by snewcomer** [comment]
@psteininger Relationships issue is fixed on master 🎉

Also there is a `1.5.0 release` issue #301 that we are focused on that would be great to get some more movement on!

**Comment by snewcomer** [comment]
I love all the work that has gone into this addon from ppl before 🙇 .  Hopefully 1.5.0 release this week!
