### ISSUE TITLE
belongsTo not properly emptying when set to `null`

### ISSUE THREAD

**Issue by nickschot** [poteto/ember-changeset#315]
## Version

1.5.0

## Test Case

#314 

## Steps to reproduce

I first spotted this in a changeset powered ember-bootstrap form w/ a power-select for (re)setting a belongsTo relationship. Works fine on 1.3.0.

## Expected Behavior

The relationship is emptied properly.

## Actual Behavior

It is not emptied :(

**Comment by nickschot** [comment]
Found the piece of code that causes this:

https://github.com/poteto/ember-changeset/blob/7bda87b2ae8f07754f7d07a122fe2efc4800918f/addon/index.js#L767-L771

**Comment by nickschot** [comment]
@snewcomer is there a need to relay anyway if the new value is not an object (mainly `null`)?

**Comment by nickschot** [comment]
@snewcomer this seems to have broken again for me on 1.6.0 even though the PR #318 is in that release.

**Comment by snewcomer** [comment]
What release did it last work in?

**Comment by nickschot** [comment]
1.3, it seems #318 also didn't fix this exact issue as the section of code that's triggered is above that (see a couple comments back). I think the problem is that it only checks if the original is an object and then returns the relay, while the true value is now `null` as it's an empty relationship.

**Comment by snewcomer** [comment]
I’m guessing this is fixed now as of 2.0z. I’ll close for now but feel free to reopen!
