### ISSUE TITLE
This line blocks reseting nested object probery

### ISSUE THREAD

**Issue by andrewfan** [poteto/ember-changeset#321]
In my application I have an object with text property
``` 
    {
       text: some.text
    }
```

In template I'm modifiing the whole object with `mut` helper
everything works fine when text string is not empty, when it is empty  I'm receving the original object
I think it break here 
https://github.com/poteto/ember-changeset/blob/462e677eea3d71f0ca1335ff4b08f8c5786a1604/addon/index.js#L786

**Comment by snewcomer** [comment]
@andrewfan What does `result` resolve to for you?  I'd accept a PR though!  I myself am kind of avoiding patch PR's for now.  Going through a rewrite in the next month or so to fix many of issues here.

`1.3.0`  is a good version to stick to. 👍

**Comment by snewcomer** [comment]
Nested setters with the `mut` helper will sadly be a paind point until we come up with a better solution.  ONly one that I got working is in JS land.

https://github.com/poteto/ember-changeset/pull/335#issuecomment-451677035

**Comment by snewcomer** [comment]
@andrewfan I believe we have this fixed in v3.0.0-beta series (although requires `ember-source 3.13`).  Please re-open if that is not the case!!

ref #379
