### ISSUE TITLE
RFC: Pt. 2 - Migrate to Typescript

### ISSUE THREAD

**Issue by snewcomer** [poteto/ember-changeset#323]
Remove Flow implementation and convert to Typescript addon for better ease of maintenance in the future.

This may be of some help: https://www.twitch.tv/videos/317598546

Ref #317 https://github.com/poteto/ember-changeset/issues/322

**Comment by snewcomer** [comment]
@dorilla - I think step one here would be to remove the flow implementation first.  Then migrate to typescript.  Did a bunch over the weekend on a typescript addon and love it!  Most likely a good fit here.  

Another route is we remove the Flow implementation and leave the Typescript migration for another day after we investigate the `skipped` tests (nested implementation).  But I think one goal of this project may have been to have some sort of typed project...so perhaps we should stick with that.

**Comment by dorilla** [comment]
@snewcomer Sounds good, I can get started on the Typescript migration this week.

**Comment by snewcomer** [comment]
This is done!  Hats off to @dorilla!  `2.0.0-beta.0` released!

**Comment by jordpo** [comment]
@snewcomer so glad the add-on is on TS now! Thank you!

Do you have an example of usage of the Changeset type in a consuming project? I made a test that is a TS file that imports `Changeset` and I am getting errors around unknown properties, probably related to the proxy nature of changesets. Unknown property `get` and unknown property `errors` - both I use in my tests.

**Comment by snewcomer** [comment]
@jordpo Are you on `2.0`?  Looks like I have both of those defined in the `types` [file](https://github.com/poteto/ember-changeset/blob/master/addon/types/index.ts).

**Comment by jordpo** [comment]
Yeah I'm on `2.0` - could be a weird setting on my end.

**Comment by snewcomer** [comment]
@jordpo Can you paste the error here?  I should get something going in the dummy app in the next few weeks.
