### ISSUE TITLE
RFC: Pt. 3 - Evaluate use of native Proxy

### ISSUE THREAD

**Issue by snewcomer** [poteto/ember-changeset#324]
This is just an evaluation step.  Not necessarily saying we should go with it.  Need to evaluate after removing Relay implementation.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy

Downside is no IE support

Ref #317 https://github.com/poteto/ember-changeset/issues/323 https://github.com/poteto/ember-changeset/issues/322

**Comment by poteto** [comment]
I investigated this in https://github.com/poteto/validated-proxy, but gave up on it as there wasn't an obvious way to handle async sets and return a promise. I may have missed something though.

**Comment by snewcomer** [comment]
@poteto Great point. Do you feel like returning a promise from a setter is necessary?  Right now, `set` returns a `ValidationResult`.  It seems like it was deemed true.

Setter happens `sync`.  Validation may be `async`. However, I'm wondering about the case for returning a `ValidationResult` from `set`.  We could require the user to call `.validate()` to get a `Promise<ValidationResult>` back. 

I believe this would allow us to use Proxy and probably squash some persistent issues around our current implementation.  

Would love to hear other's thoughts as well!
