### ISSUE TITLE
[2.0.0] `Cannot read property '_internalModel' of undefined` when saving changeset created off relationship

### ISSUE THREAD

**Issue by nickschot** [poteto/ember-changeset#339]
## Version

2.0.0

## Test Case

https://ember-twiddle.com/71783e0988666e55502dfdafadc55145
The test case is basically two model instances with a one-to-one relationship. When creating a changeset like `new Changeset(this.model.post)`, save won't work properly on the changeset.

## Steps to reproduce

Click the save button in the twiddle and the error is thrown.

## Expected Behavior

Save works properly

## Actual Behavior

Somehow the scope is lost when saving the changeset, thus `this` is undefined. The spot where it's going wrong is this branch of the save code: 
https://github.com/poteto/ember-changeset/blob/d2f9cbe8d6d8f7b774fc51a39d5bdfc7c2df9fc5/addon/index.ts#L227-L235

**Comment by snewcomer** [comment]
@nickschot my initial thought is `changeset` should work with fully resolved models.  But we could `unwrap` it if necessary.  So yeah I agree with your idea. PR?

**Comment by nickschot** [comment]
Yeah I now remember that was the basic idea. I also still think unwrapping is a good idea. Especially because it's pretty easy to solve within Changeset and relatively hard to do so in a controller or component (afaik the easiest is to fully resolve all models you want to use in the route).

I'll try some more stuff and then create a PR.

**Comment by snewcomer** [comment]
The trick I use often is to wrap in resolve (to ensure thennable) `return resolve(obj).then(...);` and then performing logic in the callback.

**Comment by nickschot** [comment]
@snewcomer yes that would indeed be the way to make sure .then is available (obj might not be a promise).

The most important thing we need to define is the correct place to do this. I was thinking it would be best to do on initialization, but a quick experiment showed that the changeset itself would not be correctly loaded (init is sync).

Doing it in the `save` method works, but I'm not entirely sure if it is the correct place to handle this as this might go wrong in case the model is actually an unresolved promise instead of a proxy (i.e. relationship that was already in ember-data's store).

**Comment by snewcomer** [comment]
@nickshot does this have broader implications that just the `save` method?

**Comment by nickschot** [comment]
I am not 100% sure, the changeset is definitely working before fully resolving it. I think by adding it in the `save` method we just add support for passing a relationship and not for records that haven't been loaded yet.

Going to dig a little more this week.

**Comment by snewcomer** [comment]
`v3.6.0`!
