### ISSUE TITLE
Deeply nested properties do not trigger template getter on rollback

### ISSUE THREAD

**Issue by jasonmevans** [poteto/ember-changeset#342]
## Version
2.0.0

## Test Case
https://github.com/neighborly/changeset-test

## Steps to reproduce
We are building a generalized `form` component based on `ember-changeset` that yields a set of input fields that are automatically bound to the changeset by a `fieldName` property. The `value` of these inputs is bound by a template getter to the `this.fieldName` property within the changeset, and `onInput` is bound to `action (changeset-set this.changeSet this.fieldName) value="target.value"`. The changeset picks-up on the changes to the input; however, when the form is reset, the changes clear from the changeset, but the inputs do not reset their values. 

It seems like the `{{get}}` helper only binds to the first token in a complex property key. This does *not* happen on properties that are at the top-level of the changeset model. For example, this will occur on a `name.first` property, but not on a `email` property.

Here is a demo app that illustrates the idea: https://github.com/neighborly/changeset-test

In this demo app change both of the values in the inputs, and click the reset button. You will only see the email field reset.

## Expected Behavior
Expected behavior is that any property would update when reset.

## Actual Behavior
Actual behavior is that the deeply nested properties do not update when reset.

**Comment by snewcomer** [comment]
So just to confirm, reset clears top level properties?  Or does the input values stick around for all types of properties?  (Will 👀 at your demo later.  Thx for that!)

**Comment by jasonmevans** [comment]
Hi @snewcomer! Thanks for getting back so quickly, and sorry for the delay!

The reset does clear the top-level properties. Only properties that are nested within an object do not reset. I believe that it is due to the getter that I'm using in the template, and I think that the reset is not triggering the getter to re-compute. I believe if I add another computed property that is actually bound directly to the nested property it may update, but the idea here is to make it all work off of a `fieldName`. 

I guess one question I have is whether we are pulling values into the input field correctly, or is there a better way to bind the input to the changeset than using `{{get this.changeSet this.fieldName}}`.

Thanks again for your time on this.

**Comment by snewcomer** [comment]
@jasonmevans Checked out the repo and that looks correct.  So `rollback` isn't propagating events to the template. I'm surprised it doesn't b/c we call `notifyPropertyChange(key)` which I would assume would mark `key` as "dirty" and start the Glimmer propagation chain with `get` even though `key` may be a nested path.

I think you are right and is a bug but not sure how to fix.  I'm guessing the changeset doesn't have "actual" changes on them after reset though.

I'd be curious what a `{{log (get this.changeSet this.fieldName)}}` prints out.

Also I think you may have a good idea there.  Create a computed with cache breaking keys and bind the input to the computed.  I'd be really curious if that works b/c nested property levels has been a major source of pain so far.

**Comment by jasonmevans** [comment]
@snewcomer I spent a little bit of time researching the computed property solution, but came up with a conundrum. Computed properties are created when the class is defined, and at that time you don't know what the value of the `this.fieldName` property would be to bind to. 

```
export default class extends Component {
  @changesetGet('changeset', 'a.b.c')
  public get value() { ... }
}
```
vs.
```
export default class extends Component {
  public fieldName: string;

  @changesetGet('changeset', this.fieldName)
  public get value() { ... }
}
```
Here, `fieldName` isn't assigned when `changesetGet` is called to create the computed prop. Even something like `@changesetGet('changeset', 'fieldName')` wouldn't really work.

I did a little digging, and I believe the approach that [`ember-classy-computed`](https://github.com/simplabs/ember-classy-computed) took is promising. Their method enables dynamically updating the computed property based on an unknown key, but the examples they show use `observable`'s, which are deprecated. I'm going to see how it works using a CP instead. 

There's also this post, but it's not quite the same thing:
https://dockyard.com/blog/2015/10/23/ember-best-practices-dynamic-dependent-keys-for-computed-properties.

Regarding `{{log (get this.changeSet this.fieldName)}}`, I added that to the template for `InputText`, and the values are logged when the component boots, but they don't update when changed. The `<ul>` list of changes in the example shows the changeset is updating, though. 

I'll post again when I have more findings from `ember-classy-computed`.

**Comment by jasonmevans** [comment]
Also, is `ChangesetDef` the correct type for the `Changeset` class? What's the best way to type a changeset?

**Comment by jasonmevans** [comment]
@snewcomer We have some news. My colleague, @josemarleudke, and I have come up with a workaround for the problem we are experiencing. In the end, we did not use `ember-classy-computed`, but took some inspiration from it. The simplest solution turned out to be to implement a `changeset-get` template helper similar to `changeset-set` that calls the correct changeset getter, and registers observers to notify the helper of when to recompute its values. 

We have opened PR https://github.com/poteto/ember-changeset/pull/351 with our fix for this. It includes some tests to illustrate the problem/solution in addition to some small updates to your `README.md`. I'd love your feedback when you have time, but no rush as we are using the template helper in our projects as a stop-gap. 

Thanks!

**Comment by erichonkanen** [comment]
hey, using latest 2.1.2 with `{{changeset-get}}` and having same issue where a nested key isn't being updated after it's changed.

e.g. `new Changeset({ params: { query: '' }})`, `<input value={{changeset-get changeset "params.query"}}>` If I mutate the value of changeset.get('params.query'), the input in the template will not update.

also here is a way to spy on a dynamic dependent key in:
```
    // define dynamic computed selected at runtime.
    defineProperty(this, 'selected', computed(`changeset.${this.name}`, {
      get() {
        if (this.changeset) {
          return this.changeset.get(this.name);

        }
        return null;
      },
    }));
```

**Comment by rreckonerr** [comment]
@erichonkanen I have similar problems trying to set/get values for nested changesets.

Changeset in the parent component is not able to track changes in a child component. Given an object like 
```js
changeset: {
    address: {
        zip_code: '0000'
    }
}
```
and an attribute `this.attribute = 'address.zip_code'`.
```js
  init(...args) {
    this._super(...args)

    defineProperty(
      this,
      'value',
      computed(`model.${this.attribute}`, {
        get() {
          return get(this, `model.${this.attribute}`)
        },
        set(key, value) {
          set(this, `model.${this.attribute}`, value)
          return value
        }
      })
    )
  }
```
If you switch to changeset.set(), changeset will be able to track the changes
```js
  init(...args) {
    this._super(...args)

    defineProperty(
      this,
      'value',
      computed(`model.${this.attribute}`, {
        get() {
          const model = get(this, 'model')
          return isChangeset(model) ? model.get(this.attribute) : get(this, `model.${this.attribute}`)
        },
        set(_, value) {
          const model = get(this, 'model')
          isChangeset(model) ? model.set(this.attribute, value) : set(this, `model.${this.attribute}`, value)
          return value
        }
      })
    )
  }
```
But now  changeset.rollback() is not triggering child's CP's getter and changeset.save() does

**Comment by rreckonerr** [comment]
That's the solution
```js
  init(...args) {
    this._super(...args)

    defineProperty(
      this,
      'value',
      computed(`model.${this.attribute}`, `model.{_content,_changes}` {
        get() {
          const model = get(this, 'model')
          return isChangeset(model) ? model.get(this.attribute) : get(this, `model.${this.attribute}`)
        },
        set(_, value) {
          const model = get(this, 'model')
          isChangeset(model) ? model.set(this.attribute, value) : set(this, `model.${this.attribute}`, value)
          return value
        }
      })
    )
  }
```
