### ISSUE TITLE
ChangeSet does not support direct property-getting

### ISSUE THREAD

**Issue by DLiblik** [poteto/ember-changeset#344]
Looking for an enhancement to support direct property getting on a changeset:

Instead of `changeset.get('myProp')`, support `changeset.myProp`

This appears to is related to the issue discussed here:
https://github.com/emberjs/ember.js/issues/16521 

I believe the fix is straightforward and laid out clearly there, but I could be totally wrong!

**Comment by snewcomer** [comment]
@DLiblik Not sure if it is straightforward or not.  We are implementing our own `unknownProperty` below.  I'm unsure of the behaviour with `.myProp` in Ember, but I do believe it leads to undesirable results.  Perhaps I'll have time to dig in, but if you did as well, would love to experiment with any solutions!

https://github.com/poteto/ember-changeset/blob/master/addon/index.ts#L124

**Comment by snewcomer** [comment]
I think I will close this for now.  Not sure we want to modify the underlying behaviour of the proxy.  I wish there was an easier solution but not sure at this point.
