### ISSUE TITLE
Typecript issue related to `validate` method

### ISSUE THREAD

**Issue by bakerac4** [poteto/ember-changeset#347]
Im getting a TS error in my project related to the `validate` method.

You can pass in 0 arguments to `changeset.validate()` to validate the whole changeset, but the typings don't allow that. 

I believe you need something like

```
validate: (key?: string | null) => (Promise<null> | Promise<any | IErr<any>> | Promise<Array<any | IErr<any>>>),
```

**Comment by snewcomer** [comment]
good call!  2.0.1 published!
