### ISSUE TITLE
ValidatorFunc has wrong type signature?

### ISSUE THREAD

**Issue by josemarluedke** [poteto/ember-changeset#349]
The `ValidatorFunc` type has the params signature as a single object, however, in `ember-changeset-validations` each validator function returns a function that takes several arguments, not a single object.

Here is the type signature
```
export type ValidatorFunc = {
  (params: {
    key: string;
    newValue: any;
    oldValue: any;
    changes: { [key: string]: any };
    content: object;
  }): ValidationResult | Promise<ValidationResult>;
};
```

Here are a few examples:
- https://github.com/poteto/ember-changeset-validations/blob/master/addon/validators/inclusion.js#L9
- https://github.com/poteto/ember-changeset-validations/blob/master/addon/validators/format.js#L8

I would expect these to match. I realized this as I was writing some types for `ember-changeset-validations` as well writing a custom validator.

## Version
```
    "ember-changeset": "^2.0.1",
    "ember-changeset-validations": "^2.1.0",
```

**Comment by snewcomer** [comment]
@josemarluedke Would you like me to put up a PR or is this something you can take on?  Either way is good for me!

**Comment by josemarluedke** [comment]
Unfortunately I'm short on cycles at the moment. So if you could get a PR for this, that would be awesome.

**Comment by snewcomer** [comment]
@josemarluedke Sounds good!  Does it make sense to match up the ember-changeset-validations to take an object as the first argument rather than `(key, value) =>`?  Having trouble seeing how those function work with this function call - https://github.com/poteto/ember-changeset/blob/3d777266a252d352513c6833fe3fc83345da9c90/addon/index.ts#L615

**Comment by snewcomer** [comment]
v2.2.1 should have the fixes you need!  Lmk if you have any questions...basically the changeset helper has been merged into this repo.  So no breaking changes either...

https://github.com/poteto/ember-changeset/pull/373
https://github.com/poteto/ember-changeset/pull/372
