### ISSUE TITLE
Set nested collection element by index

### ISSUE THREAD

**Issue by michalo-iRonin** [poteto/ember-changeset#353]
Is it possible to set particular element of nested collection by index?

### Scenario
I have a case when I need to change relationship `projectSystem` for `externalResource` and it was handling by simple:
`externalResource.set('projectSystem', newProjectSystem);`
Unfortunately after refactor it to changeset, line above affects to base model.

I'm wondering if I can use set method according to changeset approach.
I tried something like this but it doesn't work at all:
`changeset.set('task.externalResources.1.projectSystem', newProjectSystem);`
Does it exist solution for that?

**Comment by snewcomer** [comment]
Hi @michalo-iRonin!  What about `changeset.set(task.externalResources.objectAt(1), 'projectSystem', newProjectSystem)`.  Do you happen to have a little more detail on what is going wrong/what you are trying to accomplish?

**Comment by michalo-iRonin** [comment]
Unfortunately this solution doesn't work due to key handling in `set` method ([place](https://github.com/poteto/ember-changeset/blob/7edcd8b7e9aa7191e7a64957ed2626cb7dbb3adc/addon/index.ts#L766)) therefore I got `TypeError: key.indexOf is not a function` when I tried to pass object instead of string.
I'll try to simplify example:
Excepted result:
I want to have modified `changeset` with nested relationships structure and at the same time untouched base model passed to `changeset`.
In the case of only one-to-one relationships the thing is straightforward because we can generate proper key chaining no matter how long it is. However when we have one-to-many relationship it complicates situation.
Example:
`vehicle has many wheels`
If we want to change number of wheels there is no problem by:
`changeset.set('wheels', lessWheels);`
On this level of nesting, eveything is ok but if we go deeper I can't change wheel's attribute. I didn't find notation to do that because ember array has only 5 properties (`firstObject`, `lastObject` are the closest but still I don't have any possibility to get 1 element from collection by passing its id).
Therefore set nested resource's attribute in one-to-many relationship is impossible or I didn't find solution.
`changeset.set('wheels.2.condition', 'bad')` <- something I want to achieve

**Comment by snewcomer** [comment]
I'm guessing the fundamental problem is this file.  Does this look right to you?  Is it even possible to do that type of nested setter in Ember (w/ the `2` in there)?

https://github.com/poteto/ember-changeset/blob/master/addon/utils/set-nested-property.ts

**Comment by snewcomer** [comment]
Since this is an Ember-ism and we have moved towards a more pure JS way of setting/getting in the new 3.0 series, this convenience won't be supported sadly :(
