### ISSUE TITLE
state is changed after save was rejected

### ISSUE THREAD

**Issue by alexborovkov** [poteto/ember-changeset#354]
## Version
2.1.1

## Steps to reproduce
Perform changeset.save(). Save was rejected.
Howewer dirty changes applied to changeset model.

**Comment by AleksandrBorovkov** [comment]
I understand that this is intentional behaviour, but it doesn't feel right. For example I need to do rollback after rejection. In this scenario I need additional invoke model.rollbackAttributes

**Comment by snewcomer** [comment]
Thanks for reporting!  Are you suggesting we should track error states and rollback attributes?

**Comment by AleksandrBorovkov** [comment]
It would be nice rollback attributes if save was not succeed

**Comment by shankarsridhar** [comment]
@AleksandrBorovkov 
Did you try `.catch()` on the `.save()` to handle rejection and call `rollback()` accordingly ?
alternatively you could also take take a `snapshot`, using the `snapshot()` method, before calling `.save()`, if you want to rollback to a more customizable state, on reject.
