### ISSUE TITLE
Underlying ES6 setter is not called

### ISSUE THREAD

**Issue by tschoartschi** [poteto/ember-changeset#360]
## Version
```
"ember-changeset": "^2.1.2"
"ember-cli": "~3.10.1"
"ember-source": "~3.10.0"
"ember-data": "~3.10.0"
```
## Test Case
I think that an ES6 setter of an underlying object is not called if the value in the changeset is updated. I say "think" because I'm not 100% sure since it happens in our production code which is much more involved so maybe it's also up to our setup. I tried to create a repo with steps-to-reproduce, here:

https://github.com/tschoartschi/ember-changeset-computed-setter

It is really a very basic example and should demonstrate the behaviour we are encountering in our app. In the demo example there is also a line which is strange, because I need an `Ember.run.later` which is not necessary in our real code (https://github.com/tschoartschi/ember-changeset-computed-setter/blob/a2b0d7e30d2a1eb54ed5f32fd86b26f86fef3ba4/app/models/material.js#L24).

Since we use native class syntax in our app I'm uncertain if I translated the code correctly. But nevertheless, the `setter` is not called in the case of a change to the changeset.

## Steps to reproduce

* Clone the repo from above and start with `ember s`.
* visit http://localhost:4200
* change the value in the basecolor input to rgb(215,0,0)
* it works for the native model (textarea is updated correctly)
* it breaks in the changset (textarea is not updated, furthermore because the setter is not called we get [object Object])

## Expected Behavior
It should be the same as with the native model. The `setter` of the underlying object should be called

## Actual Behavior
The `setter` is not called

**Comment by tschoartschi** [comment]
Just wanted to follow up on this issue. Not sure who is the maintainer but @snewcomer seems to be the most active community member. Did someone has a chance to look at the issue we encounter?

Thanks a lot 🙂

**Comment by snewcomer** [comment]
@tschoartschi Just curious what happens it is 

1.  just a `computed`?  
2.  Also what if you use native getters/setters like so...Do you get the same behaviour?

```js

    get basecolor() {
      const {r, g, b} = JSON.parse(this.shading);
      return `rgb(${r},${g},${b})`;
    },
    set basecolor({r, g, b}) {
      const shading = JSON.parse(this.shading);
      shading.r = r;
      shading.g = g;
      shading.b = b;
      // to be honest, I do not know why we need run.later here
      // without run.later the input is just empty :-( in our
      // production code we do not need run.later. But we use
      // native ES6 classes. Here I just wanted to use what
      // ember-cli generates when you run the command init
      run.later(() => this.set('shading', JSON.stringify(shading)), 0);
    }
```

**Comment by tschoartschi** [comment]
@snewcomer thanks for the quick response 🙂 I added native getter/setter to the repo (https://github.com/tschoartschi/ember-changeset-computed-setter).

I also created a screencast, maybe this explains the issue better? [See here: screencast-changeset.mov
](https://github.com/tschoartschi/ember-changeset-computed-setter/blob/master/screencast-changeset.mov)

What do you mean with:  `just a computed?`

**Comment by snewcomer** [comment]
@tschoartschi Those are native getters and setters in the context of a `computed`. See example above just using native getters/setters w/o the computed.  Also instead of get/set, just set it up with a `computed` property (that will be overridden when set)

**Comment by tschoartschi** [comment]
@snewcomer thanks for the quick feedback 🙂I added native getters in my repo, see here: https://github.com/tschoartschi/ember-changeset-computed-setter/blob/8531bc7a64ade0619d005952e121e18f813a2d65/app/models/material.js#L35 

Did I do something wrong with my setup? Should the setter be called?

Refactoring away from the setter to a `computed` could be easy in this example but our real code is a little bit more involved. It was very hard to distill the real problem out so I'm not sure if a refactor will be easy.

**Comment by snewcomer** [comment]
@tschoartschi I'm wondering if the setter is `collapsed` b/c we are `assign`'ing the contents.  I believe when we do a shallow clone like this, we are [triggering](https://2ality.com/2016/10/rest-spread-properties.html) setters.  Spread defines new properties rather than "setting" them.  That might be a way around this...

https://github.com/poteto/ember-changeset/blob/3d777266a252d352513c6833fe3fc83345da9c90/addon/utils/assign.ts#L4

**Comment by snewcomer** [comment]
@tschoartschi Can you let me know if this fixes your issue 🙏.  Thanks! 

https://github.com/poteto/ember-changeset/pull/366

**Comment by tschoartschi** [comment]
@snewcomer I'll try to test it within this week. Since we reported this issue in July I need to setup all the stuff and then give it a try (we implemented some workaround but I have too lookup what we did). I'll follow up as soon as I know more :-)
