### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by basz** [poteto/ember-changeset#369]
Not sure if this is a bug or if I'm simply misunderstanding usage but I noticed the following;

```
const list = changeset.get('arrayOfItems');
list.push(aNewItem);
changeset.set('arrayOfItems', list);
```

This will *not* mark the property `arrayOfItems` as changed. It does not appear in the changeset.changes. Eventhough I use `changeset.set`.

When I use the following does mark property `arrayOfItems` as changed.

```
changeset.set('arrayOfItems', JSON.parse(JSON.stringify(list)));
```

I think I get why this is happens; the value being a reference, which did not change, but it is a little confusing...

## Version
2.1.2

## Expected Behavior
Using `changeset.set` on arrays or lists should also mark the property as changed when it's different.

**Comment by snewcomer** [comment]
See linked PR.  Thank you for the issue!  Lmk if you have any more questions!

**Comment by basz** [comment]
I see. So one *must* create a shallow copy in user land and changes are detected?... Perhaps `set('arrayOfItems', [... arrayOfItems])` is the most elegant way to do that...

But I wonder, is there a reason the library can't relieve us of that mental weight for us?

**Comment by snewcomer** [comment]
In this case you are on operating on the same array throughout the lifecycle of that object, by the time we compare both array to determine if there are `changes`, the array has the same items in the array.
