### ISSUE TITLE
`changeset` helper conflicts with ember-changeset-validation `changeset` helper

### ISSUE THREAD

**Issue by makepanic** [poteto/ember-changeset#371]
Hi,

I just upgraded from 1.x to 2.x and noticed that the `changeset` helper is now also part of ember-changeset.

It seems like this is an issue because both e-c and e-c-v export the helper.

https://github.com/poteto/ember-changeset/blob/master/addon/helpers/changeset.ts

vs

https://github.com/poteto/ember-changeset-validations/blob/master/addon/helpers/changeset.js

Is there any recommendation on how to solve this? For now I've created a custom `validated-changeset` helper in my app and rexport the ember-changeset-validations helper

I guess we could also filter the ember-changeset tree and remove the helper if ember-changeset-validations is installed.

## Version
2.1.3

## Steps to reproduce
Have ember-changeset and ember-changeset-validations

## Expected Behavior
`changeset` helper should work with the ember-changeset-validations syntax

## Actual Behavior
`changeset` helper from ember-changeset is used

**Comment by makepanic** [comment]
This might not be an issue of ember-changeset but the way the addon trees are merged when using typescript, see https://github.com/typed-ember/ember-cli-typescript/issues/724#issuecomment-516865882

**Comment by snewcomer** [comment]
@makepanic Thanks for the report!  I believe we do have an issue - if you have both packages installed, how do you exclusively use the `ember-changeset-validations` helper?  I would assume the trees are merged.  However, I think they both approximately do the same thing but the second argument - `ember-changeset` takes a function whereas the validations one takes an object.

I like the idea of renaming it.  What do you think?

**Comment by makepanic** [comment]
You're right. 

What would you suggest that the ember-changeset-validations helper to be called?

**Comment by snewcomer** [comment]
@makepanic My proposal would be to merge features from `ember-changeset-validations` into this repo.  Specifically allowing an object to be passed to the changeset helper.  What do you think?

**Comment by snewcomer** [comment]
I think I have identified what we need to do.  The `changeset` helper needs to either take `ValidatorFunc | ValidationMap` as the second argument.  In the case you give us a `ValidationMap`, we wrap it in a function.  Will have the changes up today.

**Comment by snewcomer** [comment]
v2.2.1 now includes the features from `ember-changeset-validations`!  Lmk if you have any more questions and thank you for talking this through with me!

**Comment by makepanic** [comment]
Thanks. I've upgraded out app to use 2.2.1 and it seems to work fine.

Thanks for the hard work :)
