### ISSUE TITLE
Throws if an array of strings is provided as error argument to addError()

### ISSUE THREAD

**Issue by jelhan** [poteto/ember-changeset#376]
Accordingly to types `addError()` method excepts an array of strings as second argument but if doing so throws an assertion `Error must have value.`.

The type declaration:

https://github.com/poteto/ember-changeset/blob/95d9602719bfb1c8dbea00683f081d309b2644eb/addon/index.ts#L383-L386
https://github.com/poteto/ember-changeset/blob/95d9602719bfb1c8dbea00683f081d309b2644eb/addon/types/validation-result.ts#L2

The assertion being thrown:

https://github.com/poteto/ember-changeset/blob/95d9602719bfb1c8dbea00683f081d309b2644eb/addon/index.ts#L390

This might be caused by `isObject(error)` returning `true` for an array of strings.

Faced this bug while upgrading from `v2.1.2` to `v2.2.1`.

**Comment by snewcomer** [comment]
OH great observation!  Will look into it today if you don't get to it first!

**Comment by jelhan** [comment]
Thanks for the quick fix!
