### ISSUE TITLE
TypeScript issues in 3.0.0

### ISSUE THREAD

**Issue by billdami** [poteto/ember-changeset#422]
## Version
ember-changeset@3.0.0 
ember@3.15.0
ember-cli-typescript@3.1.3

## Expected Behavior
TypeScript types are exported from the package. e.g. 
```ts
import { ChangesetDef } from 'ember-changeset/types';
```

## Actual Behavior
TypeScript types exports seemed to have been removed from the 3.0.0 stable release. 

It looks like the type defintions were still present up until v3.0.0-beta.17.. is there a different recommended path for TypeScript support in v3.0.0?

**Comment by snewcomer** [comment]
Yes I forgot about this.  Thank you for the issue.  We can probably export the types (from `validated-changeset` now)...

https://github.com/validated-changeset/validated-changeset

**Comment by snewcomer** [comment]
I put up a PR.  Lmk what you think and if there is anything else you need!  #423

**Comment by billdami** [comment]
@snewcomer looks good, thanks very much!

**Comment by snewcomer** [comment]
@billdami I'm now sort of curious how this new file interops with a TS project.  (sry for the bombardment of questions...) Do you happen to know?  Does it actually work for you?

Another follow up I need to document is that the types are available from `validated-changeset`.  As a transitive dep, I'm wondering if I need to add to DefinitelyTyped....

**Comment by billdami** [comment]
@snewcomer yeah so after you mentioned that the types are now coming from the `validated-changeset` package, I realized I was able to just do this in 3.0.0:
```ts
import { BufferedChangeset } from 'validated-changeset/dist/types';

export default  class Foo extends Component {
  changeset?: BufferedChangeset;
}
```
And that works fine. So I'm assuming your re-export should as well.

**Comment by billdami** [comment]
@snewcomer actually the one thing i'm unsure is, is although you'll be able to manually import the types from there to type things, is if TS will automatically associate these with `ember-changeset`'s own exports. Or if you'll also need to declare a .d.ts file that declares an `ember-changeset` module. 

Right now this:
```ts
import Changeset from 'ember-changeset';
```
Gives me a TS error
```
Could not find a declaration file for module 'ember-changeset'. '/.../node_modules/ember-changeset/index.js' implicitly has an 'any' type.
  Try `npm install @types/ember-changeset` if it exists or add a new declaration (.d.ts) file containing `declare module 'ember-changeset';`ts(7016)
```

**Comment by snewcomer** [comment]
Good point!  Yeah we might need an `index.d.ts` at the root of the addon?  If I do, I'm not sure how I'll be able to associate and export `validated-changeset`'s types in that file though....


I'll look around the community if I can find an answer and lmk if you happen to come across anything as well!
