### ISSUE TITLE
Missing types in v3

### ISSUE THREAD

**Issue by josemarluedke** [poteto/ember-changeset#424]
Prior versions exported a few types that are useful.

```
ValidationResult,
ValidatorMapFunc,
ValidatorAction,
ChangesetDef
```

It seems that instead of using `ChangesetDef`, we should not use `BufferedChangeset`. Confirm?

Also, not having a type definition for the module is a pain for typescript users.

For example, I'm importing `import Changeset from 'ember-changeset';`  Typescript will complain that there is no type definition for this module. We should include an `index.d.ts`.

## Version
3.0.1

**Comment by snewcomer** [comment]
@josemarluedke 👋 I'm currently trying to figure out the best way to do this.  Would appreciate any help or thoughts!

So the types are in `validated-changeset/types` or `validated-changeset/types/types`.  Should we re-export from `ember-changeset/types`?  Does this work for you?  What should be included in the top level `index.d.ts`?

**Comment by snewcomer** [comment]
@josemarluedke Lmk if the latest 3.0.3 works for you!

**Comment by josemarluedke** [comment]
I'm testing out the last version, I will keep posting as I find things. 

Here is the first one: 

Interestingly, I had to import the types from `ember-changeset/addon/types` and not `ember-changeset/types`.

**Comment by josemarluedke** [comment]
Type for `ValidatorMap` is missing. This is useful when working with the `lookupValidator` from `ember-changeset-validations`.

**Comment by snewcomer** [comment]
ok try 3.0.4!

**Comment by josemarluedke** [comment]
@snewcomer I believe v3.0.4 fixes all my issues at the moment. 

Here is a commit in a project applying some changes to accommodate the new types: https://github.com/josemarluedke/frontile/pull/30/commits/0a1bd2d5ca34b8d2c01a5e047b9058291164bcfb

I will close this issue and if I find anything else I will let you know. Thank you for working on all these things.
