### ISSUE TITLE
Ember Data `isValid` property is not shadowed by the changesets `isValid`

### ISSUE THREAD

**Issue by ohcibi** [poteto/ember-changeset#434]
I've setup a basic example to demonstrate one problem with changesetting ember data models: https://github.com/ohcibi/changeset-test

The problem is that the models have an `isValid` property that is true by default. When one `get`s the `isValid` property from the changeset of that model the changeset ultimately fails to return the right thing in https://github.com/poteto/ember-changeset/blob/master/addon/index.js#L190

`this[key]` which is `this['isValid']` returns false so the condition for the if in that line fails (and also the `else if` which does the test for the same key in this case) and the changeset then tries to return the `isValid` of the proxied object. Since that one has an `isValid` which is `true` the changeset returns `true` as well.

My suggestion would be to test explicitly for `undefined` instead of just a falsy value. I can PR if thats an appropriate solution.

**Comment by snewcomer** [comment]
@ohcibi Phenomenal!  Yes this is a good catch.  A PR would be welcome!

**Comment by arenoir** [comment]
This is a pretty big bug and think it should be noted in the changelog that this version doesn't work with ember-data.   I have created a quick fix.
