### ISSUE TITLE
Updating a changeset Date value with a new date results in an empty object

### ISSUE THREAD

**Issue by billdami** [poteto/ember-changeset#442]
## Version
v3.0.8 

## Test Case
https://github.com/billdami/ember-changeset-date-issue
This is a working Ember app (v3.16.1) that fully demonstrates the issue.

## Steps to reproduce
1. Create a new `Changeset` with a property that contains a `Date` value. (This is crucial, if the changeset is initialized with the property being empty/`null`, the issue does not manifest.)
2. Update the changeset property later (i.e. via a form) with a new date value, e.g.
    ```js
    changeset.dateField = new Date();
    //OR...
    changeset.set('dateField', new Date());
    ```

## Expected Behavior
The changeset contains the new Date value when its later accessed, e.g. `changeset.dateField`, or `changeset.get('dateField')`.

## Actual Behavior
The changeset property is updated to just a plain, empty `{}` object.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/611458/76996372-c7814400-6927-11ea-9c2a-2cf998eb428e.gif)

**Comment by snewcomer** [comment]
3.0.9!
