### ISSUE TITLE
usage of pushErrors results in resetting of field value

### ISSUE THREAD

**Issue by roberkules** [poteto/ember-changeset#448]
## Version
2.2.5

## Test Case
https://ember-twiddle.com/05d1a9769d61c61da725e607396afaf4
(upon saving, pushErrors is called to add error on nested property)

## Steps to reproduce
change street & save

## Expected Behavior
- street field shows error state
- street field remains with changed value

## Actual Behavior
street field is reset to initial value

-----
(using pushErrors on not nested attribute **name** doesn't have the same effect)

**Comment by roberkules** [comment]
PS: in the ember-twiddle I'm using ember `3.16.3` and ember-data `3.16.2`, but in my project I'm stuck (for now) with ember `3.9.1`, thus updating to `ember-changeset 3.x` is not an option.

Using ember `3.9.x` results in a slightly different behavior. after saving, the street field remains changed until you change any of the other input fields... and then blur... now the street field is reset to its initial value.

**Comment by snewcomer** [comment]
@roberkules Just tried e-c 3.4.0 and it seems to work.  Fixes related to nested keys has gone through a massive overhaul since 2.2.5.  Sadly, upgrading to v3 series is your only option unless we can figure out a fix to backport.  Sorry about that!
