### ISSUE TITLE
Getting a value in JS doesn't return correct changed value from changeset

### ISSUE THREAD

**Issue by josemarluedke** [poteto/ember-changeset#452]
Given the following code: 

```js
export default class UserEditForm extends Component {
  model = {
    firstName: 'Initial',
    lastName: 'Last',
    mailingAddress: {
      number: '333',
      streetName: 'Market St.',
      locality: 'San Francisco',
      unit: '16',
    }
  };
  changeset = Changeset(this.model);

  @action handleAddressChange(){
    const address = {
      number: getRandomInt(10),
      streetName: getRandomInt(1000),
      locality: 'San Francisco',
    }

    console.log('Will set new address', address)

    const unit = this.changeset.get('mailingAddress.unit');
    this.changeset.set('mailingAddress', {
      ...(address || {}),
      unit
    } );
  }

  @action setAddressUnit(value) {
    const address = this.changeset.mailingAddress;
    console.log('Existing address', address)
    this.changeset.set('mailingAddress', { ...address, unit: value });
  }
}
```

After calling `handleAddressChange`, we will have a new value set in `mailingAddress`.
After calling `setAddressUnit`, we get the current `mailingAddress` and use that to combine with a new unit number. 

The expected behavior is that when getting the `mailingAddress` from `this.changeset`, it returns the nearly set address. However, it returns the original value from the model.

Please check out the demo app to see it in action.

## Version
3.2.0

## Test Case

https://github.com/josemarluedke/--changeset-glimmer/commit/10bc5c854d56bc8f63028505d5332f40ad748738

## Steps to reproduce
Check the reproduction app then:
Click "Set a new address", then:
See new address displayed, then: 
Fill a new value for the Unit, then:
See the old address displayed, with the new unit.

In the reproduction app, there is a test showing the behavior: http://localhost:4200/tests?filter=UserEditForm

## Expected Behavior
The new address should be kept in place.

## Actual Behavior
The address is updated to the old address.

cc/ @snewcomer

**Comment by snewcomer** [comment]
@josemarluedke Thank you for the issue 👏!!  Looks like I made a false assumption in validated-changeset when I first rewrote it.  As you can see from your example, the siblings are being lost when we set a key within an object already marked with `Change` class (a scenario where we have `CHANGES` already).

I have an idea how to handle.

**Comment by josemarluedke** [comment]
Thank you @snewcomer for the fix. I can confirm the lastest version fixed the problem.
