### ISSUE TITLE
isValid / isInvalid are not tracked

### ISSUE THREAD

**Issue by BryanCrotaz** [poteto/ember-changeset#455]
It is natural to want to use `isValid` or `isInvalid` in a template:

`<button disabled={{changeset.isInvalid}}>SAVE</button>`

These should therefore be tracked so that they will update in a template.

**Comment by snewcomer** [comment]
@BryanCrotaz So I think how this might work is that the properties that are tracked (`_errors`/`_changes`) is what we have annotated and are "dependencies" of `isValid`/`isInvalid`.  I would have assumed this works correctly - that is when `_errors`/`_changes` update, `isInvalid`/`isValid` is invalidated.

Now I know POJOs have to be instrumented ahead of time.  If you can't enumerate all possible keys inside the object, then you have to "reset" the trackable property to trigger invalidation.  

So perhaps I am wrong or mislead.  But do you have an easy reproduction?

> isValid
https://github.com/validated-changeset/validated-changeset/blob/master/src/index.ts#L206

> reset ERRORS
https://github.com/validated-changeset/validated-changeset/blob/master/src/index.ts#L517

> reset CHANGES
https://github.com/validated-changeset/validated-changeset/blob/master/src/index.ts#L747

**Comment by BryanCrotaz** [comment]
isValid and isInvalid are plain functions - they're not marked with @tracked so they don't update the UI.

`disabled={{changeset.errors.length}}` works but that's not intuitive to the new developer when `isValid` exists.

**Comment by snewcomer** [comment]
To make sure we are on the same page, `isValid` is a [getter](https://github.com/validated-changeset/validated-changeset/blob/master/src/index.ts#L206).

https://guides.emberjs.com/release/upgrading/current-edition/tracked-properties/

I agree errors.length is not ergonomic.  Perhaps I should add a test to confirm and then we can go from there.

**Comment by snewcomer** [comment]
@BryanCrotaz see #456 .  Seems to be working.  Did I missing anythign?

**Comment by BryanCrotaz** [comment]
I created my changeset with the {{changeset}} helper, and used `presence` validators. That shouldn't cause a difference. But in my case whatever the isInvalid button state is at the beginning, it's the same at the end.  I'll try and create a twiddle.

**Comment by snewcomer** [comment]
@BryanCrotaz Mind trying out the latest 3.5.7 if you don't mind?

**Comment by alexlafroscia** [comment]
I'm seeing this issue as well -- a computed property defined like this

```javascript
  @filterBy('changesets', 'isInvalid', true) changesetsWithErrors;
```

Does not update as the changesets become invalid, including on version `3.6.0`

**Comment by snewcomer** [comment]
@alexlafroscia What happens if you changed this to a plain getter?  I'm a tad wary of computed/observer based reproductions with the 3.0 series w/ `@tracked`.

**Comment by alexlafroscia** [comment]
I'm actually trying that right now -- it _seems_ like that works, but I'm not exactly sure _why_ a normal getter "works" but the computed macros do not.

**Comment by BryanCrotaz** [comment]
I thought computed macros now use tracked under the hood. Maybe I’m wrong.

**Comment by snewcomer** [comment]
@BryanCrotaz @alexlafroscia This might get us what we want...

https://github.com/poteto/ember-changeset/pull/509

**Comment by BryanCrotaz** [comment]
Looks perfect
