### ISSUE TITLE
`execute` is losing the Decimal.js instance prototype

### ISSUE THREAD

**Issue by jeffsawatzky** [poteto/ember-changeset#457]
## Version
3.2.1

## Test Case
```
import Decimal from 'decimal.js';
import { Changeset } from 'ember-changeset';

function validatorFn() {
  return true;
}

let changeset = Changeset({}, validatorFn);

let decimal = new Decimal('4');
console.debug(decimal.__proto__);
console.debug(decimal.toString()); // correctly outputs 4

changeset.set('decimal', decimal);
decimal = changeset.decimal;
console.debug(decimal.__proto__);
console.debug(decimal.toString()); // correctly outputs 4

changeset.execute();
decimal = changeset.decimal;
console.debug(decimal.__proto__);
console.debug(decimal.toString()); // should output "4" but outputs "[object Object]"
```

Console output is
```
Object { name: "[object Decimal]", abs: abs(), … }
4
Object { name: "[object Decimal]", abs: abs(), … }
4
Object { … }
[object Object]
```

## Steps to reproduce
1) Store a Decimal instance in a changeset
2) Executes the changeset
3) Try to get the Decimal value back and notice that it's prototype is incorrect

## Expected Behavior
The Decimal object I get back should work

## Actual Behavior
The Decimal object I get back has lost it's prototype and doesn't work

**Comment by snewcomer** [comment]
@jeffsawatzky I created a PR and it looks like all the tests are passing.  Thoughts on what I missed?

https://github.com/validated-changeset/validated-changeset/pull/31

**Comment by jeffsawatzky** [comment]
@snewcomer interesting. Perhaps it has something to do with Decimal.js specifically? Or maybe because I am importing Decimal.js using ember-auto-import?

I updated my test with some extra info:
```
import Decimal from 'decimal.js';
import { Changeset } from 'ember-changeset';

let changeset = Changeset({});

let decimal = new Decimal('4');
const originalProto = Object.getPrototypeOf(decimal);

console.debug('------------- Original instance -------------');
console.debug('instanceof: ' + (decimal instanceof Decimal));
console.debug(' __proto__: ' + decimal.__proto__);
console.debug(
  'same Prototype: ' + (Object.getPrototypeOf(decimal) === originalProto)
);
console.debug('toString(): ' + decimal.toString()); // correctly outputs 4

console.debug('------------- Before Executing the Changeset -------------');
changeset.set('decimal', decimal);
decimal = changeset.decimal;

console.debug('instanceof: ' + (decimal instanceof Decimal));
console.debug(' __proto__: ' + decimal.__proto__);
console.debug(
  'same Prototype: ' + (Object.getPrototypeOf(decimal) === originalProto)
);
console.debug('toString(): ' + decimal.toString()); // correctly outputs 4

console.debug('------------- After Executing the Changeset -------------');
changeset.execute();
decimal = changeset.decimal;

console.debug('instanceof: ' + (decimal instanceof Decimal));
console.debug(' __proto__: ' + decimal.__proto__);
console.debug(
  'same Prototype: ' + (Object.getPrototypeOf(decimal) === originalProto)
);
console.debug('toString(): ' + decimal.toString()); // should output "4" but outputs "[object Object]"

export default {};
```
and the output is as follows:
```
------------- Original instance-------------
    instanceof: true
__proto__: NaN
same Prototype: true
toString(): 4
------------- Before Executing the Changeset-------------
    instanceof: true
__proto__: NaN
same Prototype: true
toString(): 4
------------- After Executing the Changeset-------------
    instanceof: false
__proto__: [object Object]
same Prototype: false
toString(): [object Object]
```
So maybe it's because the original prototype is NaN that is messing up the merge deep?

**Comment by jeffsawatzky** [comment]
@snewcomer I actually inspected the code of Decimal.js a little, and it is defining the Decimal calls a little weirdly. It does something like:
```
let P = {
  toString() {
    return '42';
  }
};

function Decimal() {}
Decimal.prototype = P;
```
And if you use this class now, the above debug statements spit out:
```
------------- Original instance-------------
    instanceof: true
__proto__: 42
same Prototype: true
toString(): 42
------------- Before Executing the Changeset-------------
    instanceof: true
__proto__: 42
same Prototype: true
toString(): 42
------------- After Executing the Changeset-------------
    instanceof: false
__proto__: [object Object]
same Prototype: false
toString(): [object Object]
```
So after the `execute` it is losing it's `toString` from the prototype

**Comment by snewcomer** [comment]
@jeffsawatzky What happens when you start with a decimal key on the changeset?  Does that change anything?

```
let changeset = Changeset({ decimal: new Decimal() }, validatorFn);
```

**Comment by jeffsawatzky** [comment]
@snewcomer to be honest I didn't try starting with a decimal because even if it helped fix my issue, the value can be nullable.

However, I did notice that in my test when I import `Changeset` from `ember-changeset` I get the issue, but when I import `Changeset` from `validated-changeset` I don't.

So the issue doesn't exist in `validated-changeset` which is why your tests don't catch them, but it does exist in `ember-changeset`

**Comment by snewcomer** [comment]
@jeffsawatzky wow.  Ok that is really good information.  The only difference w/ e-c is that it uses `Ember.set` rather than just plain JS in `v-c`

https://github.com/poteto/ember-changeset/blob/aa6cd34f54ddf1d8c280bc64a7e3953733df2e9c/addon/index.js#L108

I'm not sure of a solution though.  I'd be curious if there was a minimal repo that we could determine who is at the culprit.

**Comment by snewcomer** [comment]
ref #465

**Comment by snewcomer** [comment]
Can you try the latest 3.3.4 if you don't mind?

**Comment by jeffsawatzky** [comment]
Seems to be fixed.
