### ISSUE TITLE
Issue with @tracked

### ISSUE THREAD

**Issue by gvocale** [poteto/ember-changeset#468]
I am running into issues setting and consuming a changeset at the same time.

I have the following in a Glimmer component:
```js
// component.ts
export default class Dummy extends Component {
  @tracked changeset: BufferedChangeset;

  get otherProperty() {
    return this.changeset.property
  }
 
  @action
  setProperty() {
    this.changeset.set('property', {});
  }
}
```
```hbs
// template.hbs
{{log this.changeset.property}}
```

I get the following error:
```js
Error: Assertion Failed: You attempted to update [object Object].property to "[object Object]", but it is being tracked by a tracking context, such as a template, computed property, or observer. In order to make sure the context updates properly, you must invalidate the property when updating it. You can mark the property as `@tracked`, or use `@ember/object#set` to do this.
```

As you can see `changeset` is marked as `@tracked`, but that didn't seem to help.

If I just set the value, without consuming it in the template or another property, I don't get the error.

**Comment by gvocale** [comment]
Just to add to it, the first time doing `this.changeset.set('property', {});` it works, from the second time onwards, the error is thrown.

**Comment by snewcomer** [comment]
👋 Thank you for the issue!  I have a PR open to provide better ergonomics around Proxy `set`.  One note is `@tracked` is good for properties that are `set` (replaced).  It looks like you might be modifying keys on the object instead.  I'm not 100% sure if this works or not.

**Comment by snewcomer** [comment]
This is in fact a problem.  At the `validated-changeset` layer, we use play JS setters.  However, using `Ember.set` is problematic when starting from `{}` and you want to set a nested path `user.email`.  Currently investigating this limitation and alternative solution in `validated-changeset`.

**Comment by basz** [comment]
I'm hitting this error too...

**Comment by snewcomer** [comment]
Tracking it.  A bit unexpected behaviour from `Ember.set` so it isn't a straightforward refactor.  Hope to get it fixed today.

<img width="667" alt="Screen Shot 2020-05-09 at 3 46 15 PM" src="https://user-images.githubusercontent.com/7374640/81578851-3dba8980-9360-11ea-84c7-0e531476a9a2.png">

**Comment by basz** [comment]
anything I can do to help?

**Comment by snewcomer** [comment]
Thanks @basz!  I have a solution in the linked issue.  Effectively b/c Ember.set does not handle `Ember.set({}, 'user.name', 'foo')`, we need to keep our own `setDeep` logic but when property assignment happens at each level of the tree, we use `Ember.set`.  Will look to get in and update e-c by the end of the day!
