### ISSUE TITLE
Setting value deeper than depth 1 removes siblings

### ISSUE THREAD

**Issue by grubmar** [poteto/ember-changeset#470]
Looks like setting a value deeper than depth 1 removes siblings.
```
  deep1: {
    deep11: {
      deep111: "first",
      deep112: "second",
      deep113: "third"
    }
  }
```

 `changeset.set('deep1.deep11.deep112', 'Hello World')`

after this the object is :

```
  deep1: {
    deep11: {
      deep112: "Hello World"
    }
  }
```

It does work with depth 1 but not with depth 2 (and I guess, same with even deeper values)

## Version
3.3.4

## Test Case
https://github.com/grubmar/changeset-issue-repo

## Steps to reproduce
1. Start server.
2. Click both buttons

## Expected Behavior
![image](https://user-images.githubusercontent.com/36658689/81708025-4484f180-9471-11ea-903f-f1b74313a604.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/36658689/81708223-5f576600-9471-11ea-986c-24e13144f479.png)

**Comment by grubmar** [comment]
While trying to avoid this issue by setting a complete object instead of a single deep-key, I found another issue with the set function for deeper values.
Added to the linked repo a additional case where it will overwrite a deep-key with a object twice. First time it works as expected, but the second time it does not apply the object properly, it adds an additional child-key with the passed object, instead of updating it:
![image](https://user-images.githubusercontent.com/36658689/81797438-15bd5880-950f-11ea-9194-2477a5e3cfb3.png)

Might has to do with the `changes` as the first time the changeset is not dirty for this key.

Also a short video to reproduce the issue:


![changeset-issue-object](https://user-images.githubusercontent.com/36658689/81797797-88c6cf00-950f-11ea-9797-7c3cedd32b5f.gif)


I would have expected the template to render as following:
![image](https://user-images.githubusercontent.com/36658689/81797942-b27ff600-950f-11ea-8198-017d12147cf5.png)

**Comment by grubmar** [comment]
well, looks like I should use the `changeset-get` helper as mentioned in the docs, thought is not needed anymore, the first issue seems to work now (my bad, I apologize..). 
But the second thing, with setting a deep value twice seems to still be an issue :thinking:

**Comment by snewcomer** [comment]
@grubmar Thanks for the issue!  This certainly seems like a bug.  Will get a fix up by tomorrow!

Failing test here: 

https://github.com/validated-changeset/validated-changeset/pull/39

**Comment by grubmar** [comment]
Im still facing this issue (or now I'm facing this issue):

Given this resource:

```
const resource = {
  styles: {
    colors: {
      main: {
        sync: true,
        color: "#3D3D3D",
        contrastColor: "#FFFFFF",
        syncedColor: "#575757",
        syncedContrastColor: "#FFFFFF",
      },
      accent: {
        sync: true,
        color: "#967E6E",
        contrastColor: "#ffffff",
        syncedColor: "#967E6E",
        syncedContrastColor: "#ffffff",
      },
      ambient: {
        sync: true,
        color: "#FFFFFF",
        contrastColor: "#3D3D3D",
        syncedColor: "#FFFFFF",
        syncedContrastColor: "#575757",
      },
    },
  },
};
```

and doing the following:

```
const changeset = new Changeset(resource);
// just to output the current content
changeset.get('styles.colors.main');

// setting deep-value
changeset.set('styles.colors.main.sync', false);

// siblings missing now
changeset.get('styles.colors.main');
```

![image](https://user-images.githubusercontent.com/36658689/82181575-1a08bd80-98e3-11ea-998c-8a441ee3f4c9.png)


@snewcomer should I open a new issue?

**Comment by snewcomer** [comment]
@grubmar Ya this is a somewhat tough problem.  I'll open a new issue and detail what is going on.  Basically, we may have to implement some recursive proxy based solution. 

What you are seeing in the output is the `CHANGES` on the changeset.  As a result, if we return out a recursive proxy, we could trap each property access and return either on `CHANGES` (on changeset) or on the `CONTENT` (original model).

THank you for sticking with this issue!

**Comment by snewcomer** [comment]
https://github.com/validated-changeset/validated-changeset/pull/45

Ok I think I have a solution.  Let me know what you think!!

**Comment by grubmar** [comment]
> [validated-changeset/validated-changeset#45](https://github.com/validated-changeset/validated-changeset/pull/45)
> 
> Ok I think I have a solution. Let me know what you think!!

looks good to me. 
unfortunately I'm not completely aware of e-c/v-c internals so I do not really can make a useful review
