### ISSUE TITLE
Validate a computed property or native getter?

### ISSUE THREAD

**Issue by andreyfel** [poteto/ember-changeset#474]
Let's say I have an object with 3 boolean fields:
```
class MyObj {
  isOptionOne;
  isOptionTwo;
  isOptionThree;
}
```
I want it to be valid when at least one of these 3 fields is true. How do I do it with the changeset validation?

I could make a getter
```
get isOptionSelected() {
  return this.isOptionOne || this.isOptionTwo || this.isOptionThree;
}
```
and validate against that new property. 
```
isOptionSelected: validateInclusion({ list: [true] })
```
But it won't work with the changeset because the changes are in the changeset and when the getter is evaluated, `this` contains original object.
If I try to define that getter on the Changeset by extending it, its value is just undefined.

Any tips how I can do the desired validation?

**Comment by snewcomer** [comment]
@andreyfel Interesting!  I'm trying to understand how we could accommodate such as use case.  I would have thought extending the changeset would have worked (and perhaps the only viable solution).  Happen to have a small reproduction?

**Comment by andreyfel** [comment]
@snewcomer I've added a failing test here: #482.
Changeset doesn't even try to evaluate the computed property.
It only checks `changes` for a given key and then goes to the original object to look for the value there. https://github.com/validated-changeset/validated-changeset/blob/893f08209f8dcbcc05be12b78970173bb0aee6da/src/index.ts#L785

**Comment by andreyfel** [comment]
@snewcomer here is an attempt to fix this scenario https://github.com/validated-changeset/validated-changeset/pull/54

**Comment by andreyfel** [comment]
@snewcomer I updated the test case and bumped the validated changeset version.
By some reason the test was passing even without bumping validated changeset version. Apparently they don't respect the lock file? Not sure if you consider this as an issue.

I think this PR can be merged to verify the behavior on the level of ember-changeset?

**Comment by snewcomer** [comment]
3.5.0!  Thanks for all your work!!!
