### ISSUE TITLE
Support `isValid`, `isDirty`, `isInvalid`, `isPristine`, etc. for individual properties

### ISSUE THREAD

**Issue by acburdine** [poteto/ember-changeset#48]
Something that would be a nice-to-have for Ghost's usage (currently refactoring the validations to use ember-changeset) would be methods (computed properties perhaps?) on the changeset object that allow checking of individual properties for valid/invalid/dirty states.

Based on the current structure this shouldn't be too terribly difficult, but wanted to make sure this is a desired feature before going ahead and creating a PR for it 😄

**Comment by poteto** [comment]
Do you need these properties in the template, in JS land, or both? Right now, there is a subset of the properties you listed:

Individual valid state: `changeset.change.firstName` will give you the changed value, and if a value is present then it is both valid and dirty for that prop
Individual invalid state: `changeset.error.firstName.{value,validation}` will give you the error object containing the value and validation message, and if an error is present it's both invalid and pristine

I'm not sure if the above is sufficient for your usecase. That said, I could see a use for method(s) that can return for individual properties. I'm unsure how a CP would work though, I don't think it would make sense to have a multiple CPs (4) per virtual property that's set. What are you thinking the API would be?

**Comment by acburdine** [comment]
After taking a crack at the validations usage, the property subsets will work just fine for the use-case I'm implementing.

However, if there's still interest in methods for determining state for individual properties, I'm happy to implement them 😄  I agree that individual CPs would be a lot for each virtual property (I was basing this a bit off of `ember-cp-validations`, which I had used before, but that addon follows a different philosophy)

The api could probably look like the actual property names, but take a key parameter. Something like:

```js
isInvalid(key) {
    if (isNone(key) {
        return get(this, 'isValid');
    }

    return get(this, `error.${key}`);
}
```

same for other methods.

**Comment by poteto** [comment]
Great! Those properties already exist on the changeset instance, so we'd need to give the methods a different name. I generally prefer `isFoo` naming conventions for predicate CPs / methods so I'm not super sure what I'd call these.

Random idea: what about something like this?

```js
changeset.get('firstName.isValid');
```

Then in changeset:

```js
props = {
  isValid(key) {
    // logic
  },
  isInvalid(key) {
    // ...
  }, ...
}

unknownProperty(key) {
  let path = key.split('.');
  let value = this._valueFor(key);
  
  if (path.length > 1 && isNone(value)) {
    let [_key, status] = path;
    return isPresent(props[status]) ? props[status](_key) : value;
  }

  return value;
}
```

I think this would be kinda nice and still work if there is actually a value on `firstName.isValid`. What do you think? I might have overlooked something

**Comment by acburdine** [comment]
That sounds like a good idea. I'll see what I can implement at somepoint later this week!

**Comment by TNAJanssen** [comment]
What is the current status?

**Comment by estshy** [comment]
@acburdine What you think about @TNAJanssen solution?

**Comment by snewcomer** [comment]
This seems to be mostly completed.  Lmk if anybody else has any more requests!
