### ISSUE TITLE
Bug: Async belongsTo() presence validation

### ISSUE THREAD

**Issue by andreyfel** [poteto/ember-changeset#489]
Reproduction: #488.

This is a regression bug that appeared in 3.4.0. It is reproducible only for async relationship. For sync belongsTo() it works as expected.

The problem is that an empty object  `{}` comes to the validator as a value. And it comes from BufferedChangeset.[CHANGES] which got this value in a BufferedChangeset getter:
https://github.com/validated-changeset/validated-changeset/blob/36c28a6e5083045dbacd5801f17df35382379b3d/src/index.ts#L904

The value must be a `null` or ObjectProxy of null (in case of async belongsTo)

**Comment by snewcomer** [comment]
`v3.6.0`!
