### ISSUE TITLE
`Maximum call stack size exceeded` error when accessing relationship

### ISSUE THREAD

**Issue by miguelcobain** [poteto/ember-changeset#502]
When I try to access a property of a belongs to relationship of a changeset object, I get a `Maximum call stack size exceeded` error. The error comes out wether you use the `changeset-get` helper or not.

Example:
```hbs
{{this.changeset.belongsToRelationship.name}}
```
or

```hbs
{{changeset-get this.changeset "belongsToRelationship.name"}}
```

The changeset object was created using 
```js
this.set('changeset', new Changeset(this.model));
```

Here's what the error looks like:
![Screen Shot 2020-06-07 at 04 11 11](https://user-images.githubusercontent.com/631691/83959462-fea32980-a874-11ea-8492-783e1648c25f.png)

From what I was able to understand, I'm getting into an infinite loop around the `safeGet` here on the validated-changeset package: https://github.com/validated-changeset/validated-changeset/blob/e1dd9a65d19fd1e269b48049855421d32a041cfd/src/utils/object-tree-node.ts#L49 

The key that it loops in is `__CUSTOM_TAG_FOR__ember159149944767897589162650__`.

I tried to PR a failing test, but it seemed like relationships are pretty will tested in ember-changeset, so I'm a bit lost now. :(

I'm using version 3.5.5, but this also happened with every other 3.X version.

Using ember and ember data 3.18.

**Comment by snewcomer** [comment]
👋 Thanks for the issue.  I originally had a check to make sure it was not inherited.  Looks like that property is not inherited so the fix below wouldn't have worked (as you indicated).

https://github.com/validated-changeset/validated-changeset/commit/12405077c385c61b1265de1019a1f3ee4bf47157

At first glance, I am a little lost.  Pushed up a failing test for now...

**Comment by snewcomer** [comment]
This seems like a less than ideal work-around but I wonder if we cache (WeakMap for the ObjectTreeNode instance) the "gotten" keys for `content` only (`content` is assumed frozen until we `execute` the underlying changes)

**Comment by miguelcobain** [comment]
@snewcomer I'm really not familiar with validated-changeset or ember-changeset internals, so I can't really talk about the validity of your workaround suggestion. :)
But it would be really good to have a workaround in userland for everyone that ends up in here.

**Comment by snewcomer** [comment]
closed with `v3.5.6` and `changeset-get`!

**Comment by miguelcobain** [comment]
@snewcomer could it be possible that this error is still happening when the belongsTo relationship is `null`?

**Comment by miguelcobain** [comment]
@snewcomer I was able to reproduce this in a failing test this time: #504

**Comment by snewcomer** [comment]
Probably.  We effectively need to something like this PR so we don't go down the deep deep hole of trying to iterate ember-data objects

https://github.com/validated-changeset/validated-changeset/pull/67

**Comment by snewcomer** [comment]
`3.5.7`!

**Comment by miguelcobain** [comment]
I can confirm that it is working now. Thanks a lot @snewcomer !
