### ISSUE TITLE
pendingData property to get resulting object with changes applied

### ISSUE THREAD

**Issue by RuslanZavacky** [poteto/ember-changeset#512]
Have a feature request?
=======================

I am working on a use case, where ember-changeset is not the single solution to validate data. We use JSON Schema to validate fields, and some of those fields are dynamic. So their validation is derived from the server, when we've got that schema. 

Our validation process goes through 2 stages: 
(1) validate changeset 
(2) validate through JSON schema

To pass proper data to JSON schema for validation, we have to call `changeset.execute().data` as we need a current set of fields.

But here is an issue: if customer pressed Submit on form once, and there are errors in Changeset, it won't give me latest execute() to apply, those making JSON schema validation incorrect, as it won't run on latest data that customer entered.

```
/**
   * Executes the changeset if in a valid state.
   *
   * @method execute
   */
  execute() {
    if (this.isValid && this.isDirty) {
      let content = this[CONTENT];
      let changes = this[CHANGES];
      // we want mutation on original object
      // @tracked
      this[CONTENT] = mergeDeep(content, changes, { safeGet, safeSet });
    }

    return this;
  }
```

--

Proposal would be, to add a `force` mode to execute, if it is passed - it would apply the data, regardless if it is valid or not. Something like:

```
  execute({ force = false } = {}) {
    let shouldExecute = (this.isValid || force) && this.isDirty;

    if (shouldExecute) {
      let content = this[CONTENT];
      let changes = this[CHANGES];
      // we want mutation on original object
      // @tracked
      this[CONTENT] = mergeDeep(content, changes, { safeGet, safeSet });
    }

    return this;
  }
```

Another option could be to introduce a separate method that can return full object with pending changes applied.

Is there something I might be missing in such approach? If not, I can open a PR to add it.

**Comment by RuslanZavacky** [comment]
Update: Approach changed in PR, instead of changing `execute()` method, new `pendingData` property is introduced. For now it would work only for POJOs, and if you want to merge two ember-data models, you still have to use `execute()` method.

**Comment by snewcomer** [comment]
3.7.0!

**Comment by RuslanZavacky** [comment]
Thank you!
