### ISSUE TITLE
Loosing belongsTo Proxy Object after calling prepare

### ISSUE THREAD

**Issue by mwalper** [poteto/ember-changeset#515]
## Version
v3.6.1

## Test Case
After setting a belongsTo relationship on an EmberData model and calling changeset .prepare(...), the relationship is undefined. 

## Steps to reproduce
Always

## Expected Behavior
The related Object should be present in changes.

## Actual Behavior
The belongsTo is undefined.

It seems related to https://github.com/poteto/ember-changeset/issues/339
but since prepare is called before save, that's no help.

**Comment by snewcomer** [comment]
@mwalper What does your `prepare` callback look like?  I have a test locally and it looks like it is working.  If you had the full example, that would be great!

**Comment by snewcomer** [comment]
Closing for now since we have tests for this.  Feel free to reopen!
