### ISSUE TITLE
Incorrect behaviour when using get / changeset-get helper i.c.w. nested objects

### ISSUE THREAD

**Issue by jeroen-hoekstra** [poteto/ember-changeset#518]
## Version
3.7.1

## Test Case
[Ember Twiddle](https://ember-twiddle.com/a0ed6ea40e958c9ea1e6e84b26eb1d78)

## Steps to reproduce
Open console. Toggle values are false. Toggle the first. Value becomes true. Toggle it again. It becomes undefined.

I also tried replacing all get helpers with the changeset-get helper. I can then toggle one of them once and see the log once. For the second (non toggled) toggle element I get the following console error: **Assertion Failed: Cannot call get with 'hidden' on an undefined object**. 

What I also find strange is that I need to use this:
`{{#each-in (get changesetObj 'directions.content') as |presetNr property|}}`

instead of this:
`{{#each-in (get changesetObj 'directions') as |presetNr property|}}`

to make the loop work.

## Expected Behavior
The toggle will have true or false value when toggled

## Actual Behavior
Initial toggle value is false. When toggled once, it becomes true. When toggled again it becomes undefined. (See output of the log template helper).

**Comment by snewcomer** [comment]
@jeroen-hoekstra Can we make sure we try 3.20 before I dig in?  Thanks for the issue!

#516 
https://github.com/emberjs/ember.js/pull/18961

**Comment by jeroen-hoekstra** [comment]
Updated our code base to Ember 3.20. That fixes the issue. I must say that I use the `get` template helper instead of the `changeset-get` helper. If I use the `changeset-get` helper I'm receiving the following js error:

![Screenshot from 2020-07-28 09-10-57](https://user-images.githubusercontent.com/42991987/88639533-2f594f80-d0bd-11ea-97ad-55dd3de1946d.png)

Initially the value both toggles are false. When I toggle the first it's value get changed to true and the error appears.

So the question is, should I be using the `changeset-get` helper or is it ok to use the normal `get` helper?

**Comment by snewcomer** [comment]
Awesome!  Ya I think either should work.  

This PR should fix it...

https://github.com/poteto/ember-changeset/pull/522
