### ISSUE TITLE
Changeset doesn't set boolean property with a default value

### ISSUE THREAD

**Issue by jordpo** [poteto/ember-changeset#519]
## Version
3.7.1

## Steps to reproduce
Initialize a new Changeset with a boolean property with a default value. 

## Replication
https://ember-twiddle.com/c3ab24b800d2fbebcde9b0a9bc1cdef2?openFiles=controllers.application%5C.js%2C

## Expected Behavior
The property value will toggle from true, to false, back to true.

## Actual Behavior
The property toggles initially from false to true, to false, then stays stuck at false

**Comment by jordpo** [comment]
Please note - the setting only breaks when there is a default value that is a boolean. If the property is initialized as undefined, there is no breakage with setting.

**Comment by jordpo** [comment]
I updated the twiddle with a workaround. The error is the `ember-changeset` implementation of `safeSet`. If we use the `safeSet` implementation that `validated-changeset` uses, the problem seems to be fixed.

**Comment by jordpo** [comment]
As an aside, the Readme seems to have incorrect instructions for extending from base and how to pass in options. `Changeset` takes 4 arguments not 3 and the options is the last arg.

**Comment by snewcomer** [comment]
ref https://github.com/poteto/ember-changeset/pull/516

I believe this was fixed in the 3.20-beta series of Ember.js.

ref https://github.com/emberjs/ember.js/pull/18961

> Readme seems to have incorrect

Fixed!

**Comment by jordpo** [comment]
Thanks @snewcomer ! Can you explain how the Ember issue fixes the issue that I was seeing with setting boolean values on the changeset?

**Comment by snewcomer** [comment]
Basically, there is a "cache" in `dev` mode that provides helpful debugging/assertions.  The "cache" had a value of `true` and when you tried to set it to `false`, it just returned the cached value, `true`.

**Comment by jordpo** [comment]
Thanks. That makes sense. I'll close this issue and wait for 3.20 to be released.
