### ISSUE TITLE
first property in nested object is not validated again

### ISSUE THREAD

**Issue by basz** [poteto/ember-changeset#521]
Hi,

I have some properties in a changeset. some of those are POJOs with more POJOs. Initially, validations defined for these nested properties run, however when I change the value again the `changeset.errors` does not contain the validation error anymore. This happens only for the first property or property that contains a validation inside the POJO.

This seems to be consistent and repeatable...

Using the latest versions.

**Comment by snewcomer** [comment]
Hi!  Do you have a failing test you might be able to contribute to the repo?

**Comment by basz** [comment]
suspecting it is ember-bootstrap or ember-bootstrap-changeset-validations https://github.com/kaliber5/ember-bootstrap-changeset-validations/pull/30

**Comment by snewcomer** [comment]
What version might that be?  Making sure it isn't the same class of problems like this one - https://github.com/poteto/ember-changeset/issues/519#issuecomment-660787406

**Comment by basz** [comment]
I'm using ember lts 3.16. I'll do a quick test with 3.20 to check...

**Comment by basz** [comment]
Seem to be the culprit...I've updated my app to 3.20 and this problem seems to have been resolved.

https://travis-ci.org/github/kaliber5/ember-bootstrap-changeset-validations/builds/716497258

**Comment by snewcomer** [comment]
Ok closing!  Lmk if you have other problems.
