### ISSUE TITLE
Initial set on the empty object, when calling execute().data gives a wrong data object

### ISSUE THREAD

**Issue by RuslanZavacky** [poteto/ember-changeset#529]
## Version
3.8.1

## Test Case
https://github.com/poteto/ember-changeset/pull/530

## Steps to reproduce
Create a new changeset with an empty initial object, set new value, call execute and get `data`. On initial merge, data will have `value` propagated I guess from `Changes` object when merging.

```
let c = Changeset({});
c.set('org.usa.ny', 'any value');

let data = c.execute().data;
```

## Expected Behavior
`data` to be:

```
{
  org: {
    usa: {
      ny: "any value"
    }
  }
}
```

## Actual Behavior
```
{
  org: {
    usa: {
      ny: {
        value: "any value"
      }
    }
  }
}
```

**Comment by RuslanZavacky** [comment]
It seems that if there is a nested object, this check is only validating single level. I guess it should be expanded to see if there is Change instance on any nested level.

<img width="534" alt="Screenshot 2020-08-14 at 13 15 21" src="https://user-images.githubusercontent.com/103556/90239483-41165300-de30-11ea-8722-f8635645af6d.png">

**Comment by snewcomer** [comment]
Appreciate the issue!  `v3.8.2`

**Comment by RuslanZavacky** [comment]
Thank you @snewcomer 🙏
