### ISSUE TITLE
Tracked properties should be compatible with computed properties and macros.

### ISSUE THREAD

**Issue by arenoir** [poteto/ember-changeset#535]
## Version 
ember-changeset: 3.8.2
ember-source: 3.16 LTS

## Test Case

https://github.com/poteto/ember-changeset/pull/534

## Steps to reproduce

Create a computed property that is dependent on a changeset tracked property. 

https://github.com/poteto/ember-changeset/pull/509#issuecomment-644813585

## Expected Behavior

Changes to a changesets tracked properties should notify dependent computed properties.

## Actual Behavior

Changes to a changesets tracked properties does not notify dependent computed properties.

**Comment by snewcomer** [comment]
closing since ref PR was closed!
