### ISSUE TITLE
Feature request to change constructor case to not break eslint "new-cap" rule

### ISSUE THREAD

**Issue by rsmith-cs-ux** [poteto/ember-changeset#541]
Hi there!

When constructing a Changeset, the capitalization of the function doesn't play well with es-lint rules for `new-cap` seen here: https://eslint.org/docs/rules/new-cap.

```
this.changeset = Changeset(this.user, lookupValidator(userValidator)); // <-- Breaks the eslint rule
```

If it could be changed to be lowercase, or follow a standard constructor with the `new` keyword then this wouldn't need a special exception rule in the eslint config.

```
this.changeset = changeset(this.user, lookupValidator(userValidator)); // <-- Works no problem :)
```

Thanks!

**Comment by snewcomer** [comment]
Oh interesting!  Never new of   Does your lint rules run on dependencies as well?

**Comment by rsmith-cs-ux** [comment]
Apparently it does?  Our initial reaction when seeing it was "how rude rule! We don't control that library." but I guess because we're calling the function within our code it doesn't like it ¯\_(ツ)_/¯

**Comment by JamesS-M** [comment]
I've be using it like `this.changeset = new Changeset(this.user, lookupValidator(userValidator));` without any issues. That should satisfy your lint rule!

**Comment by JamesS-M** [comment]
Oh I see, sorry I misunderstood the problem 😄

**Comment by snewcomer** [comment]
`import { Changeset as changeset } from 'ember-changeset';`

How about this?

**Comment by rsmith-cs-ux** [comment]
That is another workaround.  I locally have added the exception to our lint rule but I was thinking it would be better to handle it at this level for others.  If I'm the only one hitting the issue though I'm happy to leave it alone :)

**Comment by snewcomer** [comment]
Happy to provide another solution alongside exporting `Changeset` func (or accept a PR for one that effectively exports but calls original `Changeset` function).  How common is this lint rule?

**Comment by snewcomer** [comment]
Happy to accept a PR reexporting a `changeset` function.  Closing for now.
