### ISSUE TITLE
Unable to `mergeDeep` with your data. Are you trying to merge two ember-data objects?

### ISSUE THREAD

**Issue by rwwagner90** [poteto/ember-changeset#543]
This is more of a question, but may possibly be a bug. We recently updated to 3.9.0 and we're getting a lot of:

```
Unable to `mergeDeep` with your data. Are you trying to merge two ember-data objects?
```

Any tips on debugging what could be causing this?

**Comment by tibomogul** [comment]
Happening to us also, with just one dirty string attribute. The model was loaded with relationships included, if that helps.

**Comment by snewcomer** [comment]
I can look late tomorrow.  I can't remember what it fails on when trying to merge.  I'm pre5ty sure it works if you are only setting properties on the ed object.  A test example would be greatly appreciated!

**Comment by rwwagner90** [comment]
This seems to be an issue if you have any `hasMany` arrays. We're not modifying the `hasMany` at all, but simply using `changeset.myArrayNameHere` as a `selected` property in power select breaks ember-changeset. `changeset.myArrayNameHere.content` seems to work okay, but there are many types of subtle issues here.

**Comment by snewcomer** [comment]
So the problem we start with is the circular dependency with `Store`.  Moreover, we can't accurately detect an Ember Data object.

I have an idea though.  If we `catch` merging two objects that can't be merged, we just return `source`, thus assuming our `CHANGES` is what should be the new `CONTENT`.  @rwwagner90 What do you think?  This means; however the original model you passed into the Changeset won't be modified.  I think that is ok though.

https://github.com/poteto/ember-changeset/pull/545/files#diff-23bc747111c286d51052642a3229c961R160

**Comment by snewcomer** [comment]
@rwwagner90 @tibomogul Would you mind taking a look at these tests and let me know how your situation was different?  I originally thought this error was unlikely to happen but my tests obviously haven't taken into account your use cases!

https://github.com/poteto/ember-changeset/blob/master/tests/integration/main-test.js

**Comment by rwwagner90** [comment]
@snewcomer if you have a `hasMany` array and use it as `selected` in a multiple power-select, you'll get the error. If you use the underlying `content` it works, but it used to work without the need for reaching further down into `content`.

**Comment by snewcomer** [comment]
I hear your case.  But some help in identifying a proper test would help us get a solution. (ie. not installing power select)

**Comment by jaredgalanis** [comment]
@snewcomer I'm working with @rwwagner90 on this same issue and it appears that what may be happening is that a call to the relationship itself on a `changeset` returns a proxy, regardless if you use a `changeset.get` or not. Is this expected?

**Comment by snewcomer** [comment]
@jaredgalanis Do you happen to have a pared down example I could use for a test?  What is passed to the changeset?  A model with hasMany `Changeset(user)`?  If we can make this as simple as possible, then I can look into a fix.

**Comment by jaredgalanis** [comment]
@snewcomer here's a failing test demonstrating this: https://github.com/jaredgalanis/ember-changeset/commit/e3b7c72cf7877dcff01639a5e16ac97c3515c8b0
