### ISSUE TITLE
Set value bug after resetting to original value

### ISSUE THREAD

**Issue by mattiasamilon** [poteto/ember-changeset#558]
Thank you for contributing!
- Thank YOU for the amazing work!

Think you found a bug?
- Yes, at least I think so.

## Version
'3.10.0'

## Steps to reproduce
After instantiating a new ChangeSet, first change the value of an attribute, then change back to the original value, then try to change the value again.

## Expected Behavior
The value should be set to the new one specified.

## Actual Behavior
The value is not changed, it seems frozen.

**Comment by snewcomer** [comment]
@mattiasamilon What version of Ember are you on.  There was a bug that has subsequently been fixed and was only an issue in dev mode.

https://github.com/poteto/ember-changeset/issues/532
https://github.com/emberjs/ember.js/pull/18961
