### ISSUE TITLE
changeset.destroy() is not a function

### ISSUE THREAD

**Issue by jonr-luma** [poteto/ember-changeset#571]
I just updated from ember-changeset 2.x to 3.10.5, and no longer have access to the `.destroy()` method on changeset. I also noticed that `.destroy()` is mentioned in the readme, but is no longer on the documented list of methods available. Did `.destroy()` get removed, or is this a bug? Happy to provide more details if needed. :) 

## Version

3.10.5

## Expected Behavior

When I call `.destroy()` on a changeset, the changeset is destroyed without issue.

## Actual Behavior

I get this error: `Uncaught TypeError: this.changeset.destroy is not a function`
I also confirmed that `this.changeset` exists and is a changeset.

**Comment by snewcomer** [comment]
👋  @jonr-luma.  So this is because we used to extend EmberObject.  However, we are just a plain class now.  Do you have a particular need to call destroy?  Happy to idea-ate based on your app.

https://api.emberjs.com/ember/3.24/classes/EmberObject/methods/destroy?anchor=destroy

**Comment by jonr-luma** [comment]
@snewcomer Nope, no particular need for me to call that as long as it's not needed by ember-changeset any more. :) In that case, could we update the README section on the merge method to no longer refer to the `.destroy()` method? I'd be happy to open up a PR to remove that text. :) 

Looking at the text at the very bottom of the method:
>Note that both changesets A and B are not destroyed by the merge, so you might want to call destroy() on them to avoid memory leaks.

https://github.com/poteto/ember-changeset#merge
