### ISSUE TITLE
Api keys conflict with setting and getting on changeset

### ISSUE THREAD

**Issue by JimSchofield** [poteto/ember-changeset#628]
## Version
3.15.0

## Repo

https://github.com/JimSchofield/ember-changeset-bug

The failing test is located at `/tests/unit/changeset-test.js`

## Expected Behavior
```js
const thing = Changeset({ attributes: { thing: 'description' } });

thing.attributes // expect { thing: 'description' }, but not the case

thing.data.attributes // shows { thing: 'description' }

```

I expect that there would be no collision between internals of changesets and the changeset instance I'm making

## Actual Behavior

I believe there is an internal property `attributes` that is conflicting with the key on my object above

**Comment by JimSchofield** [comment]
**update**: At first I  suspected this was a key name collision, but I've updated the repo with another case where changeset does not set a value and it is for sure not a key name collision.

**Comment by snewcomer** [comment]
@JimSchofield This is the way we implemented to support nested objects.  I made one major assumption though.  The middle of the tree wasn't important.  Only the leaf keys were in use by users.  Did I make a bad assumption?

```
thing.attributes.thing === 'description'.
```

https://github.com/poteto/ember-changeset/pull/379

Notes you can `unwrap()` to get the object.

https://github.com/validated-changeset/validated-changeset/blob/b3f7f63ca2c0213ad6c81ee0084380ef0e8e6f6c/test/index.test.ts#L1031
