### ISSUE TITLE
moment converts to proxy on changeset creation

### ISSUE THREAD

**Issue by bgolla** [poteto/ember-changeset#629]
## Version 

    "ember-changeset": "^4.0.0-beta.1",
    "ember-changeset-validations": "4.0.0-beta.2",

## Steps to reproduce
    let x = new Changeset({ foo: moment() });
    console.log(x.foo instanceof moment); // returns false
    console.log(x.foo); //returns Proxy {changes: {…}, content: Moment, proxy: Proxy, safeGet: ƒ, isObject: ƒ, …}

## Expected Behavior
Returns moment instance instead 

## Actual Behavior
Returns Proxy

**Comment by snewcomer** [comment]
@bgolla Thank you!  Is there a minimal test and failing assertion (using this repository's test suite) that shows this bug?

**Comment by snewcomer** [comment]
@bgolla https://github.com/poteto/ember-changeset/pull/636#issuecomment-1064763004

**Comment by snewcomer** [comment]
https://github.com/poteto/ember-changeset/issues/628#issuecomment-1065797210

**Comment by veelci** [comment]
@snewcomer Why did you close this? Nothing has been done to fix this issue?
