### ISSUE TITLE
Ember Data models remain dirty after a server error

### ISSUE THREAD

**Issue by christophersansone** [poteto/ember-changeset#65]
Hi there!

Love this addon.  Actually I love all of your addons, @poteto. Thank you for always providing such elegant solutions to common problems!

One of the main reasons I am using `ember-changeset` now is to handle rolling back ember data relationships.  Currently an ember data model can rollback attributes but not relationships, so this is a nice solution.

However, I have a use case with ember data that I am finding challenging.
1. Create a changeset based on a DS.Model.
2. Make some changes to the changeset that will result in a server error, then call `save()`.
3. When it fails, the underlying model remains in a dirty state.
4. If the user were to leave the page without officially canceling changes (e.g. by clicking a Cancel button), the model will stay dirty.

The only solution I see today is to reset the changeset on `Route.deactivate`, `Controller.resetController`, or `Component.willDestroyElement`, but that is quite far from the source of the issue.  Is there a better solution?  How do others handle this today?

I believe an elegant solution would be to have a `changeset.reverse()` method, which is basically the opposite of `execute()`.  Just as `execute()` applies the changes to the underlying model without clearing the list of changes, `reverse()` would reverse the changes to the underlying model without clearing the list of changes.  This way, a `save` action may look something like this:

```
changeset.save()
  .then(() => { /* ... */ })
  .catch(() => {
    get(this, 'model.errors').forEach(({ attribute, message }) => {
      changeset.addError(attribute, { validation: message });
    });
    changeset.reverse();
  });
```

This way, the user would not have lost their changes, and the underlying model would be made pristine again.  The changeset can be safely discarded without needing to perform a final rollback.

(Ultimately I would love to see a more DDAU approach to Ember Data, where the models are read only from the server (data down), you create a changeset and submit it to the server (actions up), and a successful result will update the model from the returning payload (data down).  Let me know if you'd be interested in collaborating on that! :smile: )

**Comment by poteto** [comment]
Thank you, and sorry for the late reply!

I like the idea of `reverse`, I was thinking of implementing it as part of the undo/redo feature I'm working on. Basically we would have to figure out the original values for each key in the list of changes and store it somewhere, then try restoring those values when the changeset is executed.

Right now if you're using Ember Data, could you do what you want with [`rollbackAttributes`](https://github.com/emberjs/data/blob/v2.6.0/addon/-private/system/model/model.js#L657-L675)? (Sidenote: The undo/redo feature would work independently of this method)

**Comment by christophersansone** [comment]
Thanks for the response!  I didn't realize the changeset was not already storing the original values.  It seems like a property's original value could be stored when `set` is called, something like this:

```
_storeOriginalValue(key) {
  this._originalValues = this._originalValues || {};
  if (!this._originalValues.hasOwnProperty(key)) {
    let content = get(this, CONTENT);
    this._originalValues[key] = get(content, key);
  }
}
```

Then the original values object would be reset upon `clear()`.

In Ember Data, `rollbackAttributes` works fine for basic attribute changes, but it does not rollback changes to relationships.  So yes, it works a lot of the time, but not all the time.  I need to solve for those edge cases, and I'd love a single conventional way to do so.  I believe that this addon plus some effort to make a DDAU approach to Ember Data is the answer.  I'm hoping to spend some evenings on it this week... hopefully I'll have an addon to share as a result!

**Comment by curtisgr** [comment]
@christophersansone how are you handling tracking changes to the many side of the one-to-many relationship?  Take these two examples:

```
// market has many potatoes
// potato belongs to market

init () {
  let market = store.createRecord('market', {});

  let potato = store.createRecord('potato', {
    market: market
  });

  set(this, 'market', market);
  
  this.changeset = new Changeset(get(this, market));
},

someActionHappening() {
  let changeset = get(this, 'changeset'); // this is market

  let anotherPotato = store.createRecord('potato');

  get(changeset, 'potatoes').pushObject(anotherPotato);

  // changeset.potatoes and market.potatoes both include anotherPotato
}
```


```
// market has many potatoes
// potato belongs to market

init () {
  let market = store.createRecord('market', {});

  let potato = store.createRecord('potato', {
    market: market
  });

  set(this, 'potato', potato);
  
  this.changeset = new Changeset(get(this, potato));
},

someActionHappening() {
  let changeset = get(this, 'changeset'); // this is potato

  let anotherMarket = store.createRecord('market');

  set(changeset, 'market', market);

  // changeset.market and potato.market are not the same
}
```

In the first case, pushing a record into the hasMany side of the relationship updates the changeset and the underlying model, but calling set on the belongsTo side of the relationship updates only the changeset (as desired) while leaving the underlying model alone.  Conceptually, I like to use `pushObject/addObject` and `removeObject` when working with one-to-many relationships.  How do you work around this?

**Comment by christophersansone** [comment]
@curtisgr Hmm, my understanding is that `ember-changeset` only tracks changes to the properties of the top-level object.  For example, calling `market.set('potato', potato2)` will be tracked, but calling`market.set('potato.color', 'brown')` will not be tracked.  The same is true for changing the contents of an array: replacing the entire array will be tracked, but changing the elements will not be tracked.  This is true even without the added complexity of Ember Data relationships.

I recently started building my own Ember Data replacement.  There are several quality ones out there, but I'm finding that none of them solve "pending changes" elegantly.  Hopefully it will see the light of day some day...

**Comment by snewcomer** [comment]
Any level of nested is now tracked!

Also, for your solution, extending an EmberChangeset is now possible!

https://github.com/poteto/ember-changeset#extending-the-base-ember-changeset-class
