### ISSUE TITLE
Setting a value to null does not allow it to enter any value after that

### ISSUE THREAD

**Issue by rajeshbnv1994** [poteto/ember-changeset#654]
Hi

Settings a the value to null, it not allowing me to enter any value after that and it is only happening in development build

and production build it is working as expected.
 
Any suggestions or help would be appreciated.

**Comment by snewcomer** [comment]
@rajeshbnv1994 I would need a reproducible example scenario to look into and fix this.

**Comment by SergeAstapov** [comment]
@snewcomer I wonder if this line https://github.com/poteto/ember-changeset/blob/master/addon/utils/merge-deep.js#L8 needs to be

```js
return !!value && typeof value === 'object' && value !== null;
```

due to `typeof null === 'object'` in JS

**Comment by rajeshbnv1994** [comment]
@SergeAstapov  you are correct, when i did debug that line is causing issue, but as @snewcomer requested , i might create a scenario and give more details
