### ISSUE TITLE
undo redo 

### ISSUE THREAD

**Issue by poteto** [poteto/ember-changeset#69]

**Comment by scazz010** [comment]
Hi! 

I extended ember-changeset to support history & undo/redo for a project - it's currently released as a separate addon - https://github.com/scazz010/ember-changeset-history

If you wanted to pull this into part of the core addon, I'd be happy to make a PR - but I'm not 100% sure it makes sense - extra code/memory usage for something that people don't seem to be asking for. Mostly, just pushing this out there to see what you think!
Cheers,

**Comment by snewcomer** [comment]
closing for now!
